### ISSUE TITLE
boot-looping after install

### ISSUE THREAD

**Issue by duch3201** [Vanilla-OS/iso-builder#10]
after installing vanillaOS on my laptop it's just boot-looping
i've tried the auto partitioning as well as manual and both resulted in the same thing happening

**Comment by Teh404Gal** [comment]
Is your system EFI or BIOS?

**Comment by duch3201** [comment]
> Is your system EFI or BIOS?

efi

**Comment by Teh404Gal** [comment]
This might be related to to an internal report im gonna cross post it there

**Comment by Teh404Gal** [comment]
Try to go into the efi shell and navigated to the thumbdrive and boot from the efi file itself
