### ISSUE TITLE
Missing VPN options

### ISSUE THREAD

**Issue by kdwk** [Vanilla-OS/iso-builder#101]
### Issue Description

There are several VPN configuration settings present in Fedora but not Vanilla OS.

![Screenshot from 2023-01-23 11-25-35](https://user-images.githubusercontent.com/39268094/213961162-3f0a296f-b02f-4be2-bcb0-2fe45afcfcbd.png)
Fedora -> Settings -> Network -> VPN -> +

![Screenshot from 2023-01-23 11-28-49](https://user-images.githubusercontent.com/39268094/213961214-4a86cbb2-2a12-48f1-b847-04deb503702a.png)
Vanilla OS -> Settings -> Network -> VPN -> +

### Steps to Reproduce

- Open Settings
- Go to Network -> VPN
- Click on +
- Observe configuration options

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
I will look into this and add the necessary packages to base, thanks for the report.

**Comment by kbdharun** [comment]
Update: On this, I figured out the missing packages, will add it later today.

**Comment by kbdharun** [comment]
Done @kdwk, after the PRs merge these will be available options in GNOME Settings:

![Screenshot from 2023-01-23 21-35-37](https://user-images.githubusercontent.com/26346867/214104333-1cd53254-2bff-4040-b99b-04830088f3c8.png)

More info: https://github.com/Vanilla-OS/vanilla-base-desktop/pull/2
