### ISSUE TITLE
Manual partitioning not available

### ISSUE THREAD

**Issue by CodeWithAlamin** [Vanilla-OS/iso-builder#103]
### Feature Description

We should be able to install the OS in a specific partition we choose and create the partitions manually.

### Rationale

I think it's a core feature of a Linux distribution and a crucial feature. Please add this feature soon. We are waiting for this.

**Comment by kbdharun** [comment]
Duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/86

Btw it is being worked on currently.
