### ISSUE TITLE
Fedora container fails to start

### ISSUE THREAD

**Issue by tommerty** [Vanilla-OS/iso-builder#106]
### Issue Description

- Fresh install from today [22.10-r6](https://github.com/Vanilla-OS/os/releases/tag/22.10-r6)
- Attempted to install multiple applications from `--dnf` but kept seeing the following response:

```
Container apx_managed_dnf is not running.
Starting container apx_managed_dnf
run this command to follow along:

 podman logs -f apx_managed_dnf

Error: OCI runtime error: unable to start container "3860fbdb4b14eb04b5991acd84b08d73436ded06a375aa2ca3ce8032de995f5b": mount `/etc/localtime` to `/etc/localtime`: Not a directory
⌬ Apx :: Failed to enter container: exit status 125
```

Above error code was taken from the Vanilla Control Center

### Steps to Reproduce

Reproduce:
- `apx install --dnf htop`

Troubleshooting steps:
- reboot
- install other software from different containers (aur for example) worked
- [Asked in Discord](https://discord.com/channels/1023243680829681704/1023245426385760267/1067170219400904804)
- Searched Discord to see if any mention of `Failed to enter container` or `apx_managed_dnf is not running` but found no results.

### On what version of Vanilla OS this happens?

22.10

### Additional Information

I noticed the `First Setup` app was also being hung up on `finihzing` but it seems it was installing things like the calendar and additional information (don't have those logs currently as I believe it's unrelated).

**Comment by Teh404Gal** [comment]
From the log it seems that the container cant find /etc/localtime
Im not on my computer to test this but what if we use a different OCI image for fedora like maybe the newest image has this bug?

**Comment by bketelsen** [comment]
I experienced this same error with the ubuntu version in apx today, and it seemed to be caused by a podman issue. I deleted the apx_managed container and did `apx init` again and it worked.

**Comment by tommerty** [comment]
@bketelsen could you tell me how you did that exactly so I can try with my dnf? Not too familiar with `apx` yet!

**Comment by bketelsen** [comment]
I think it was as simple as `podman stop apx_managed` then `podman rm apx_managed`. That deletes the container and anything you've done inside it... BEWARE.  In the case of the fedora/dnf version it is called `apx_managed_dnf` so use that name. Then just re-init the container with `apx init --dnf`

**Comment by mirkobrombin** [comment]
There was issues at dockerhub side, please follow the steps by bketelsen.

**Comment by baszczewski** [comment]
> There was issues at dockerhub side, please follow the steps by bketelsen.

Could we reopen this? Unfortunately this bug still persists. Deleting _apx_managed_dnf_ and reinit don't help at all.

**Comment by tommerty** [comment]
@baszczewski  It might be best to reference in a new issue in case they don't see this.
Screenshot provided in case you aren't sure how 😄 

 ![](https://user-images.githubusercontent.com/86270372/218506597-95bfb498-6dd8-42fe-a34a-e87a0b5accfd.png)
