### ISSUE TITLE
Apps don't follow default browser when opening links

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#107]
### Update (Issue Fixed)
I was able to fix the issue by 

- setting the default browser back to gnome web
- then reopening Firefox 
- changing the setting to Firefox 

### Issue Description

Various apps don't respect the default browser set by my system when opening links, they open links in gnome web.

### Steps to Reproduce

- use an app 
- open a link 
- it routes to gnome web instead of firefox

### On what version of Vanilla OS this happens?

22.10

### Additional Information

- r6 
- I've also uninstalled gnome web in software.. Even though it doesn't do anything 
- 
![image](https://user-images.githubusercontent.com/122128828/214325491-ca1d09c2-9daa-4af7-9299-7fa1d2f84ebe.png)

[Screencast from 2023-01-24 09-47-07.webm](https://user-images.githubusercontent.com/122128828/214325773-c1075849-a381-436a-980b-b58b18148492.webm)

**Comment by kbdharun** [comment]
Is this the Flatpak version of firefox?

**Comment by ghost** [comment]
> Is this the Flatpak version of firefox?

Yes via the software store

**Comment by kbdharun** [comment]
Weird, I tried this in my VM + PC but I didn't have this issue. All links work fine and it redirects to the correct browser be it Flatpak or installed through apx.

I think it is possible that when you changed the browser preference you didn't close the current working window, so it might have redirected to the old one.

**Comment by ghost** [comment]
> Weird, I tried this in my VM + PC but I didn't have this issue. All links work fine and it redirects to the correct browser be it Flatpak or installed through apx.
> 
> I think it is possible that when you changed the browser preference you didn't close the current working window, so it might have redirected to the old one.

Makes sense, I was able to fix the issue by setting the default back to gnome web then to Firefox again. My issue might have been, I set up multiple profiles with profile manager.
