### ISSUE TITLE
Installation of apps in an ABRoot shell fails if systemd is involved in the post-install script

### ISSUE THREAD

**Issue by Master0ne** [Vanilla-OS/iso-builder#108]
### Issue Description

The problem is that any installation to the system in an ABRoot shell fails when the post-install script of the according package tries to reload systemd for a new service script to be added and activated because that does not get executed as it detects that it's running in a chroot and the install goes wrong (as what happens with SurfsharkVPN) or aborts due to failures (as it's with VirtualBox).

### Steps to Reproduce

Install any app that involves systemd in an ABRoot shell (like VirtualBox).

### On what version of Vanilla OS this happens?

22.10

### Additional Information

Trying to fix the issues by analyzing the post-install scripts of the various packages is cumbersome if not impossible, and the problem will come back again and again with every update of such a package.

**Comment by mirkobrombin** [comment]
I am able to install and enable new units in a transaction. If the package cannot run inside an Apx container and must be installed in the root fs, then it should be repacked: https://documentation.vanillaos.org/docs/packaging/

**Comment by Master0ne** [comment]
Not sure what you mean, because obviously there is no way around to installing a VPN app (SurfsharkVPN) and VirtualBox to the root fs, but it just doesn't work, because both are trying to reload systemd during the post-install script, which fails because it detects that it's a chroot, and then then whole installation fails (as in the case of VirtualBox).

VirtualBox is a typical use case, so that's what surely a lot of users will want to install, and there is obviously no easy way to do so on VanillaOS.

P.S. Not sure who is supposed to repack such packages, because VirtualBox and SurfsharkVPN come from their own repos.

**Comment by mirkobrombin** [comment]
We are discussing to move from chroot to systemd-nspawn to support systemd during the transaction.

**Comment by Master0ne** [comment]
If that's gonna solve this issue, what do you think how quickly the move can be done?
The current situation is a rather huge issue and a real show-stopper (at least for me).

**Comment by mirkobrombin** [comment]
We will test that approach asap

**Comment by meesterexx** [comment]
Just chiming in to say I have exactly this use case; need to install both SurfsharkVPN and VirtualBox and need a working solution to installing on immutable system like Vanilla OS.
