### ISSUE TITLE
broken application windows issue

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#110]
### Issue Description

A lot of my applications are being weird and showing broken window screens

Calendar
![image](https://user-images.githubusercontent.com/122128828/215162286-5a8ddbfe-d627-4742-9207-cb912e32f01f.png)

Warp
![image](https://user-images.githubusercontent.com/122128828/215168394-299dc44a-b3c7-461a-97d0-6fc70258da97.png)

### Steps to Reproduce

- be on release 6
- use gnome calendar
- use gnome warp

### On what version of Vanilla OS this happens?

22.10

### Additional Information

- Currently on release 6 
- this happens on some flatpaks such as gnome calendar and warp

**Comment by unchartedpopsicle** [comment]
This seems to be an issue with Flatpak. https://github.com/flatpak/flatpak/issues/5268

**Comment by ghost** [comment]
> This seems to be an issue with Flatpak. [flatpak/flatpak#5268](https://github.com/flatpak/flatpak/issues/5268)

Makes sense they seem to have pushed an update for it, thanks for pointing that out 
![image](https://user-images.githubusercontent.com/122128828/215274923-20580dc3-7c1b-49fd-a159-a0a88c6cd462.png)
