### ISSUE TITLE
Login Manager screen appears too small for 4K (3840x2160)

### ISSUE THREAD

**Issue by Codes301** [Vanilla-OS/iso-builder#111]
### Issue Description

OS: VanillaOS 22.10 all (64-bit)
PC type: Desktop
CPU: AMD Ryzen 3 3200G
Gnome Version: 43.1
Window system: Wayland

The login manager does not scale up or appear large enough for 4K resolutions. 

Question, is it possible to screenshot that?

### Steps to Reproduce

Boot up Vanilla OS from either cold boot or warm boot

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
I think you can take a picture :D

I do not have a 4K setup to test it.

**Comment by fat0troll** [comment]
This is a known GDM issue, that may be fixed by placing this:

```
 # cat /usr/share/glib-2.0/schemas/93_hidpi.gschema.override
[org.gnome.desktop.interface]
scaling-factor=2
```

and running `glib-compile-schemas /usr/share/glib-2.0/schemas` from root. 

It would be nice if Vanilla OS applied this setting out of the box when detecting HiDPI display (4K and so on).
