### ISSUE TITLE
HDMI sound not recognized, wireless not showing

### ISSUE THREAD

**Issue by hrqmonteiro** [Vanilla-OS/iso-builder#114]
HDMI sound is not regognized, and the same was functioning normally on Ubuntu and Fedora

Also, i have a TPLink nano wi-fi dongle and it doesn't work. And when i try to install following [this tutorial](https://github.com/aircrack-ng/rtl8812au), which i do the same when i am on Fedora, it works normally, but here, when i run the `sudo make dkms_install` command, i am prompted with this error:

![Screenshot from 2023-01-28 21-37-14](https://user-images.githubusercontent.com/17055027/215292274-d970daec-49a6-44bd-89e7-0ba320b41dca.png)

How to fix this error and how to make the HDMI sound work?

![Screenshot from 2023-01-28 21-37-37](https://user-images.githubusercontent.com/17055027/215292282-8ae03948-9de9-4ffe-92ed-f263d71a9f6f.png)

**Comment by kbdharun** [comment]
I will check the one for HDMI sound, regarding TPLink nano, it worked fine for me in testing, I will check again now and will update here.

**Comment by lukewarmcustard** [comment]
I have the exact same issue on my Razer Blade 17 (2022) with no sound input devices appearing
