### ISSUE TITLE
Installer not showing Manual Partition

### ISSUE THREAD

**Issue by Samia-47** [Vanilla-OS/iso-builder#115]
### Issue Description

the installer is not showing option for manual partition just showing to erase whole dist.
i don't want to lose my data so please fix it.

### Steps to Reproduce

Add the Manual Partition option in the installer

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
Duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/86
