### ISSUE TITLE
KDE plasma environment request

### ISSUE THREAD

**Issue by Samia-47** [Vanilla-OS/iso-builder#116]
### Feature Description

I want to have vanilla os in KDE plasma.

### Rationale

KDE looks prety amazing and easy to use, so it will be a great oportunity to see Vanilla os in KDE plasma clothes

**Comment by GabsEdits** [comment]
From what I can tell in the Discord Server and (https://discordapp.com/channels/1023243680829681704/1037058089779744809)
This well happened sometime in the future.

**Comment by mirkobrombin** [comment]
Refer to https://github.com/Vanilla-OS/os/issues/113
