### ISSUE TITLE
extension manager says no results found

### ISSUE THREAD

**Issue by TheCorruptCat** [Vanilla-OS/iso-builder#121]
### Issue Description

when i try to install a extension it says no results found

### Steps to Reproduce

open extension manager

click on browse

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
Not able to replicate. Can you launch it from your console and post the output here?

**Comment by TheCorruptCat** [comment]
how?

**Comment by TheCorruptCat** [comment]
lol it fixed itself

**Comment by ghost** [comment]
Gnome was having outages so it couldn't reach gnome extensions

**Comment by kbdharun** [comment]
> Gnome was having outages so it couldn't reach gnome extensions

This 👆🏽 . Now, can you close this issue, since it worked?

More info here: https://status.gnome.org/
