### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by TheCorruptCat** [Vanilla-OS/iso-builder#122]
### Feature Description

support for wayland

### Rationale

wayland runs games better than x11

**Comment by ghost** [comment]
Wayland is the default I'm pretty sure

**Comment by TheCorruptCat** [comment]
it says it is x11 even if im not on gnome on xorg

**Comment by ghost** [comment]
Are you sure the app isn't running through xwayland

**Comment by TheCorruptCat** [comment]
yes

**Comment by kbdharun** [comment]
> Wayland is the default I'm pretty sure

Yes, Vanilla comes with Wayland by default.

**Comment by mirkobrombin** [comment]
Wayland is already the default. You can switch choose Xorg or wayland from the login screen. Note that some applications uses xwayland, like wine apps. 

Closing since already implemented, feel free to add more comments.

**Comment by TheCorruptCat** [comment]
ok thank you
