### ISSUE TITLE
 error creating container: exit status 125

### ISSUE THREAD

**Issue by TheCorruptCat** [Vanilla-OS/iso-builder#123]
### Issue Description

when i try to use apx it says  error creating container: exit status 125

### Steps to Reproduce

open console try apx install then you get that error

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
Duplicate of https://github.com/Vanilla-OS/apx/issues/97
This issue is being actively investigated in #dev.
