### ISSUE TITLE
how do i install ferial gamemode

### ISSUE THREAD

**Issue by TheCorruptCat** [Vanilla-OS/iso-builder#124]
### Feature Description

just asking?

### Rationale

so games can run better

### Additional Information

I have a nvidia card

**Comment by mirkobrombin** [comment]
If your games are installed as flatpak: install gamemode as flatpak. 

If your games are installed with Apx: install gamemode with Apx. 

If using ABRoot (I hope not): install gamemode using ABRoot. 

please read here: https://handbook.vanillaos.org/2023/01/11/install-and-manage-applications.html

**Comment by TheCorruptCat** [comment]
how do i install gamemode as flatpak

**Comment by mirkobrombin** [comment]
flatpak install gamemode

**Comment by TheCorruptCat** [comment]
No remote refs found for ‘gamemode’
