### ISSUE TITLE
Speech dispatcher is broken

### ISSUE THREAD

**Issue by Molitvan** [Vanilla-OS/iso-builder#126]
Hi! I'm a blind user, and I just tried VanillaOS in a vm. When I try to start the screen reader with SUPER + ALT + S, I get a speech dispatcher error saying that theres no any working output modules.

I think that this could be fix by simply including the espeak package by default.

**Comment by kbdharun** [comment]
Update on this: I recently added espeak to base. It will be present in the r7 release. Thanks for reporting the issue.

 I will let you know when the base is updated and tell you to trigger an update using `sudo vso trigger-update --now`

**Comment by kbdharun** [comment]
Update 2: The base update is already available, you can trigger an update using `sudo vso trigger-update --now` wait for it to apply then reboot.
