### ISSUE TITLE
Installing Russian (maybe, any other but English) language is broken

### ISSUE THREAD

**Issue by fat0troll** [Vanilla-OS/iso-builder#127]
### Issue Description

There is a localization issue: the system is partially localized if you choose any language besides English. 

1. The installed system only partially honors the choise in the installer (for example, many menus in Gnome are still in English after choosing Russian as installation language)
2. When trying to install locale, nothing happens:

### Steps to Reproduce

For issue 1: just select any language other than English in installer

For issue 2:

* I'm going to Settings → Language and Region → clicking on system menu item for installing new languages
* App prompts for missing packages for English → I click Dismiss
* Clicking ''install new language", then choosing Russian — after clicking OK system immediately asks for reboot
* After reboot nothing changed, the only fully installed language is still English.

### On what version of Vanilla OS this happens?

22.10

### Additional Information

This was reproduced using qemu virtual machine.

**Comment by kbdharun** [comment]
This issue was fixed yesterday in a commit to the gnome language selector. You will receive an update soon to fix this.
