### ISSUE TITLE
Applications are not available in "Gnome software"

### ISSUE THREAD

**Issue by anykate** [Vanilla-OS/iso-builder#129]
Applications have disappeared from software - as you can see from below screenshot. I am also unable to manually find apps from Gnome software. Also, I have installed some browsers (e.g. Opera / Firefox / Chromium / Brave) - these show in the applications list but are not launching upon clicking them. Please fix.

![Screenshot from 2023-02-08 20-07-36](https://user-images.githubusercontent.com/1500690/217561149-fcb1fbbf-66cc-461e-9430-25415d1c4ab7.png)

**Comment by mirkobrombin** [comment]
I faced the same issue some hours ago. I already sent a fix for this, please try upgrading the system  with `vso trigger-update —now` and reinstall flatpak `sudo abroot exec apt install —reinstall flatpak`. 

Please note that “—“ should be 2 “-“

**Comment by anykate** [comment]
Thanks!

IT worked - awesome....loving Vanilla

**Comment by ghost** [comment]
> I faced the same issue some hours ago. I already sent a fix for this, please try upgrading the system with `vso trigger-update —now` and reinstall flatpak `sudo abroot exec apt install —reinstall flatpak`.
> 
> Please note that “—“ should be 2 “-“

Worked for me too, thanks
