### ISSUE TITLE
Weird window shading issue 

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#130]
### Issue Description

It looks like there's multiple windows 

### Steps to Reproduce

- it's random

### On what version of Vanilla OS this happens?

22.10

### Additional Information

R6
![image](https://user-images.githubusercontent.com/122128828/217603884-579c0d68-af7b-4d5b-91dd-9f71ad93af56.png)

**Comment by mirkobrombin** [comment]
Those are multiple windows open, I can see the multiple layers. Be sure to not click multiple time on Save buttons since some applications does not spawn the filechooser as a modal.
