### ISSUE TITLE
Unable to open any apps, OS is broken

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#133]
I’m unable to open any apps the os is broken it seems, software store doesn’t show any apps despite having internet connection. When I navigate to Update Preferences in the software store it shows only two toggles automatic updates and automatic update notifications. The operating system seems unusable, anyone got any fixes?

**Comment by mirkobrombin** [comment]
Duplicate of https://github.com/Vanilla-OS/os/issues/129

Please search before opening new issues.
