### ISSUE TITLE
Add the Zorin Layouts app to the system?

### ISSUE THREAD

**Issue by muhdsalm** [Vanilla-OS/iso-builder#134]
### Feature Description

Add the zorin OS's 'layouts' app to the system, possibly integrated into the Vanilla OS control center, to provide window-like and mac-like layouts out of the box.

### Rationale

It is apparent that the operating system is geared towards beginners as well, so someone coming from Windows or MacOS can set the layout to their liking, without messing about with extensions. Also, I see that the extension manager is included with the system, so I assume a layouts app wouldn't be too much.

### Additional Information

This problem could potentially be solved just by adding more Desktop Environments, but I see gnome as _the_ desktop environment for beginners, so I see zorin's idea as making it more usable for those who are familiar with other layouts. Also, I am only suggesting this as Vanilla has apparently been trying to be more beginner-friendly.

**Comment by mirkobrombin** [comment]
Hi, thanks for your feedback.

I am sorry but I cannot implement this since it is not compatible with the project, that aims to be as vanilla (as in stock) as possible.
