### ISSUE TITLE
Can't install Huion graphic/drawing tablet software/driver

### ISSUE THREAD

**Issue by K0-RR** [Vanilla-OS/iso-builder#135]
### Issue Description

I use `apx install --sideload` to install the deb downloaded from the Huion website, why I try again it says it's already installed but there is no app to run. I rebooted multiple times. I also tried to install from tar file:
```
sudo /home/nacia/Desktop/install.sh
/home/nacia/Desktop
cp: cannot create regular file '/usr/lib/udev/rules.d/20-huion.rules': Read-only file system
/usr/lib
./huion/huiontablet
cp: cannot create directory '/usr/lib/huiontablet': Read-only file system
```

Next, I tried to install directly to Ubuntu base via abroot shell but since it can't access distobox directory (I guess?) it prints this:
```
root@nacia:/# apt install /home/nacia/Downloads/HuionTablet_v15.0.0.121.202301131103.x86_64.deb
Reading package lists... Done
E: Unsupported file /home/nacia/Downloads/HuionTablet_v15.0.0.121.202301131103.x86_
```

### Steps to Reproduce

Download the software and try to install it.
https://www.huion.com/download/

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
You must install the driver in the host using ABRoot instead as it is required here. Follow these steps https://handbook.vanillaos.org/2022/12/10/install-additional-drivers.html#title3

For software installed in apx, you can run it using the `apx run <package>` command. Or else you can export the icon using the `apx export <package> command. More info here https://handbook.vanillaos.org/2023/01/11/install-and-manage-applications.html

**Comment by K0-RR** [comment]
Thank you, that worked flawlessly. The step I missed at first was the "exit" command that writes changes (in this situation, that is, ifaik). Instead, I closed the terminal so I guess the changes were discarded?

Maybe there should be another warning in the "PLEASE READ CAREFULLY BEFORE PROCEEDING" section that is displayed when I enter abroot shell. Something like "the changes are only saved when a proper exit command is executed"?

**Comment by kbdharun** [comment]
> Thank you, that worked flawlessly. The step I missed at first was the "exit" command that writes changes (in this situation, that is, ifaik). Instead, I closed the terminal so I guess the changes were discarded?
> 
> Maybe there should be another warning in the "PLEASE READ CAREFULLY BEFORE PROCEEDING" section that is displayed when I enter abroot shell. Something like "the changes are only saved when a proper exit command is executed"?

Yeah, I am planning to add a line to the message.

**Comment by K0-RR** [comment]
It looks like the settings inside the app (keyboard shortcuts, for example, ctrl+z, executed by clicking buttons on the tablet) are not saving. I tried to run the Huion app as root via sudo and it changed nothing.
This did not happen on Linux Mint, and I think it has to do with the read-only filesystem (the app really should print some error in the terminal tho...)
