### ISSUE TITLE
File ... couldn't be accessed by user "_apt"

### ISSUE THREAD

**Issue by lion-artiste** [Vanilla-OS/iso-builder#136]
### Issue Description

Hello everybody, 

I installed Vanilla OS yesterday, and since there's not much documentation at the moment, I don't know if this is a bug, or if I'm understanding something wrong. I don't even know where to post it, so I post it here.

I try to install the Sitala package (a drum sampler), so I download the .deb from the developer's website, I run "apx install ./sitala-1.0_amd64.deb" while in my Downloads folder, and I get the following messages and error : 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'sitala' instead of './sitala-1.0_amd64.deb'
The following NEW packages will be installed:
  sitala
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/8545 kB of archives.
After this operation, 29.0 MB of additional disk space will be used.
Get:1 /home/lion/Téléchargements/sitala-1.0_amd64.deb sitala amd64 1.0 [8545 kB]
Selecting previously unselected package sitala.
(Reading database ... 25870 files and directories currently installed.)
Preparing to unpack .../sitala-1.0_amd64.deb ...
Unpacking sitala (1.0) ...
Setting up sitala (1.0) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
N: Download is performed unsandboxed as root as file '/home/lion/Téléchargements/sitala-1.0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

The package doesn't seem to install correctly, as far as I could observe. 
I had the same exact problem while trying to install the KXStudio repositories, which also require installing a local .deb

I also tried the following commands : 

apx install --sideload ./sitala-1.0_amd64.deb

apx enter
sudo apt install ./sitala-1.0_amd64.deb

But I always get the same error. I come from Fedora, so I'm not very familiar with apt. Please help, I'm stuck !

### Steps to Reproduce

Try to install a local .deb package with "apx install"

### On what version of Vanilla OS this happens?

22.10

**Comment by kbdharun** [comment]
Thanks for the report,

> N: Download is performed unsandboxed as root as file '/home/lion/Téléchargements/sitala-1.0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

You can avoid the message.

From what I can see the installation has been completed successfully. Now you can export the desktop entry (icon) using `apx export sitala` (outside the container).

> I installed Vanilla OS yesterday, and since there's not much documentation at the moment, I don't know if this is a bug, or if I'm understanding something wrong. I don't even know where to post it, so I post it here.

We do have some primary guides at https://handbook.vanillaos.org. [This one](https://handbook.vanillaos.org/2023/01/11/install-and-manage-applications.html#title24) is relevant for your here.

**Comment by lion-artiste** [comment]
Ok thank you, it works ! :)
