### ISSUE TITLE
VPN settings glitching out

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#140]
### Issue Description

The VPN settings sometimes disappear and then reappear

### Steps to Reproduce

- open VPN settings 

### On what version of Vanilla OS this happens?

22.10

### Additional Information

R7.5

[Screencast from 2023-02-16 09-36-10.webm](https://user-images.githubusercontent.com/122128828/219397481-254486e0-45dd-4d88-baaf-3c3ec6efb69d.webm)

**Comment by kbdharun** [comment]
I don't think this is a Vanilla-specific issue. Would you be willing to report it in GNOME GitLab here https://gitlab.gnome.org/GNOME/gnome-control-center (ping me @kbdharun over there too, will help you out)?

This might be related to Network Manager (we don't have any missing packages in it, so it is better to report it over there to get an exact response).
