### ISSUE TITLE
No Nvidia X server settings app available

### ISSUE THREAD

**Issue by K0-RR** [Vanilla-OS/iso-builder#150]
### Issue Description

I can't find this app in the menu
![nvidia-linux-display-driver-64-bit_68216](https://user-images.githubusercontent.com/43277609/221675702-7779f1d9-876f-42c7-9d47-c59731a93dc3.png)

### Steps to Reproduce

no idea

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
It's not included, you can install it via abroot: `abroot exec apt install nvidia-settings`.
