### ISSUE TITLE
No Drivers section in Vanilla OS control center

### ISSUE THREAD

**Issue by K0-RR** [Vanilla-OS/iso-builder#151]
### Issue Description

![Screenshot from 2023-02-27 19-55-43](https://user-images.githubusercontent.com/43277609/221677542-651ecb02-0c5c-4302-ab59-eb6dd297f621.png)

### Steps to Reproduce

Is there any other way to install the drivers,for example via abroot shell and then sudo apt install nvidia-driver-525 nvidia-dkms-525?

The Software & Updates app from Ubuntu lists available drivers but the Apply changes button is grayed out no matter what I choose (maybe it's just the nature of abroot for now?)
![Screenshot from 2023-02-27 20-06-52](https://user-images.githubusercontent.com/43277609/221678187-6e489262-ee93-4e32-89da-6ba29ddc4402.png)

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
Hi, we moved it to GNOME Settings, under the About section.

**Comment by K0-RR** [comment]
So the Guide needs an update. How can I run the driver updater from another DE than Gnome? I'm normally running Cinnamon.
