### ISSUE TITLE
Can't downgrade flatpak's via console 

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#152]
### Issue Description

I'm attempting to downgrade a flatpak app, but the console sends back an error stating ` not installed `

### Steps to Reproduce

Have Celeste cloud backup app installed

1. open `console`
2. `flatpak list --app`
3. `flatpak remote-info --log flathub com.hunterwittenborn.Celeste`
4. `sudo flatpak update --commit=6058531cee20d33d01a49fb3909e01cc02c55b4d0b5c4bb993e536b08a4bd939 com.hunterwittenborn.Celeste`

now an error will be displayed, `error: com.hunterwittenborn.Celeste not installed`

### On what version of Vanilla OS this happens?

22.10

### Additional Information

R8

**Comment by mirkobrombin** [comment]
Use the --user flag since all flatpaks in Vanilla are installed at user side.
