### ISSUE TITLE
USB won't boot

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#157]
### Issue Description

I guess some boot files are missing from the EFI\boot folder in the ISO, that's why the USB is not booting, and it boots back to current installed OS (Windows  10 inmy case)

### Steps to Reproduce

Add the missing boot files back, USB was booting in the previous release

### On what version of Vanilla OS this happens?

22.10

**Comment by PrincessZelda99** [comment]
My Vanilla OS won't Even Load It Up It Just Go to The Current OS i am running.

**Comment by fastrizwaan** [comment]
VanillaOS-2-testing.20240130.iso also fails to boot from usb. 

etcher is showing this:

![image](https://github.com/Vanilla-OS/live-iso/assets/1161682/ec7f48d5-be96-4461-b59d-730896efdc66)

```
[rizvan@dell-fedora amd64]$ cat VanillaOS-2-testing.20240130.sha256.txt; sha256sum VanillaOS-2-testing.20240130.iso 
50e0ed9362c2230492c004a7c829336e23db65f74e214b4a746193b4ba86623d  VanillaOS-2-testing.20240130.iso
50e0ed9362c2230492c004a7c829336e23db65f74e214b4a746193b4ba86623d  VanillaOS-2-testing.20240130.iso

```
