### ISSUE TITLE
Add a "Desktop Entry" for the "Driver Utility"

### ISSUE THREAD

**Issue by HyperAlch** [Vanilla-OS/iso-builder#158]
### Feature Description

Currently you can access the `Driver Utility` via the "About" tab in the "Settings" menu. 

However, it would be nice to have direct access to this in the Gnome Search function by adding a `Desktop Entry` for it.

### Rationale

I was told by **Dharun Krishna**, a project contributor and Vanilla OS Discord moderator to create this GitHub issue after some discussion.

**Comment by mirkobrombin** [comment]
This is intentional since the utility is installed in embedded mode: https://github.com/Vanilla-OS/vanilla-drivers-utility#other-distributions
