### ISSUE TITLE
Application Search support for 3rd party browsers

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#169]
### Feature Description

Ability to add Firefox and other browsers to Vanilla OS's application search 

### Rationale

It's convenient for quickly searching the web but not through gnome web…

### Additional Information

![image](https://user-images.githubusercontent.com/122128828/228098675-37e4fc4b-74e6-454e-b445-62e7021a0b74.png)

**Comment by GabsEdits** [comment]
This is a GNOME thing, I don't think Vanilla OS can do something about it.

**Comment by kbdharun** [comment]
I think it would work with Firefox in Debian I will check if it's the case or if only Gnome web supports it.

**Comment by mirkobrombin** [comment]
Thanks for the feedback.

We follow the upstream so we don't provide extra functionality to GNOME and its apps.
