### ISSUE TITLE
No PUB_KEY

### ISSUE THREAD

**Issue by Pirateado4Ever** [Vanilla-OS/iso-builder#17]
When I try build an iso this error apears:
GPG error: https://repo.vanillaos.org/kinetic ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE18F70058D147C8
E: The repository 'https://repo.vanillaos.org/kinetic ./ InRelease' is not signed.

What can I do to solve this?

**Comment by kbdharun** [comment]
This is intended as a repository migration is in progress to the launchpad, with many packages being updated. This will be fixed in the following ISO.

Ref: https://discord.com/channels/1023243680829681704/1023246422251950230/1040383482951635035
