### ISSUE TITLE
Add "Wipe" Feature to files app

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#176]
### Feature Description

Wipe feature from Tails OS in the files app is so convenient for securely deleting files and would be great to see in Vanilla OS 2.0

### Rationale

It increases not only privacy but security 

### Additional Information

Tails OS has this feature baked into their files app

**Comment by mirkobrombin** [comment]
Thanks for the feedback.

We follow the upstream so we don't provide extra functionality to GNOME and its apps.
