### ISSUE TITLE
Add "Remove Metadata" to files app

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#177]
### Feature Description

Remove Metadata feature from Tails OS in the files app is so convenient for securely wiping the metadata off of files and would be great to see in Vanilla OS 2.0

### Rationale

It increases privacy of sharing files 

### Additional Information

Tails OS has this feature baked into their files app

**Comment by mirkobrombin** [comment]
Thanks for the feedback.

We follow the upstream so we don't provide extra functionality to GNOME and its apps.
