### ISSUE TITLE
The repository 'https://repo.vanillaos.org/kinetic ./ InRelease' is not signed.

### ISSUE THREAD

**Issue by davidbanhos** [Vanilla-OS/iso-builder#18]
Hi ,
 
   Hope everyone is well!

   Please, I'm having the issue below running the latest code:

  `docker run --privileged -i -v /proc:/proc     -v ${PWD}:/working_dir     -w /working_dir     debian:latest     /bin/bash -s etc/terraform.conf < build.sh`

   It seems it missing the GPG missing public key access:

`...
Get:20 http://archive.ubuntu.com/ubuntu kinetic-updates/universe Translation-en [11.3 kB]
Reading package lists...
_W: GPG error: https://repo.vanillaos.org/kinetic ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE18F70058D147C8_
E: The repository 'https://repo.vanillaos.org/kinetic ./ InRelease' is not signed.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...`

[build_output.txt](https://github.com/Vanilla-OS/os/files/10045662/build_output.txt)

 Happy to help with any further information.

**Comment by Teh404Gal** [comment]
If i recall correctly this might not happen soon when the migration to launchpad happens

**Comment by mirkobrombin** [comment]
> If i recall correctly this might not happen soon when the migration to launchpad happens

Correct. The old repository is going to be archived. To use the launchpad one, get the iso from https://github.com/Vanilla-OS/vanilla-os-experiments/actions
