### ISSUE TITLE
Flatpak not preinstalled

### ISSUE THREAD

**Issue by secretmango** [Vanilla-OS/iso-builder#181]
### Issue Description

Using Image VanillaOS-22.10-all.20230226

Flatpak is not preinstalled, GNOME software doesnt show flathub but VanillaOS (apt) as source.

This makes no sense at all. Installing flatpak through

```
apx install flatpak
apx run flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

does not work too, and makes no sense.

I guess the gnome software plugin is not installed too.

### Steps to Reproduce

- Install that version
- check for `flatpak` in Terminal

### On what version of Vanilla OS this happens?

22.10

### Additional Information

Freshly installed in virt-manager. Started fine.

**Comment by kbdharun** [comment]
Hi, Flatpak is installed post installation atm in the first setup, I think you might have skipped the first setup entirely.

We have flatpak and gnome software plug-in listed there along with app images, we also display a curated list of core applications and recommended ones in the applications panel.

If you didn't install Flatpak in the first setup, I would suggest you follow the guide at https://handbook.vanillaos.org/2022/12/09/install-flatpaks.html to install it manually.

Also, apx is a container manager and it doesn't modify/install contents to base, it is done through ABRoot which is used to install drivers and other essentials in the immutable system atomically. I would suggest you take a look at the docs, handbook for more info, we have descriptive posts in our blog too on the main site.
