### ISSUE TITLE
Unpin Console from the Dash by default

### ISSUE THREAD

**Issue by DartDeaDia** [Vanilla-OS/iso-builder#187]
### Feature Description

By default Console is pinned to the Dash, but Console is thing that can be used only by technically advanced users.
So, why not to move Console to the Utilities folder by default?

### Rationale

This will make Vanilla OS more friendly for newcomers, because the command line causes a negative reaction and misunderstanding from non-technically advanced users.

**Comment by GabsEdits** [comment]
While this is possible, Vanilla OS uses the base Gnome, including where apps are located. I personally think that `gnome-console` being there is a good idea for easy access, in a way I also agree with you idea.

**Comment by jamiethecat** [comment]
We have important tools that are used in the CLI, so unpinning this wouldn't make any sense. Maybe in the future when there is a GUI for everything we have.
