### ISSUE TITLE
atlauncher does not detect have but i install java already throught flathub and apx

### ISSUE THREAD

**Issue by TheCorruptCat** [Vanilla-OS/iso-builder#192]
### Issue Description

I have java installed with apx and i also install java with flathub
atlauncher had flathub

### Steps to Reproduce

install atlauncher with flathub

use atlauncher

make a server

try to run it using the sh script

### On what version of Vanilla OS this happens?

22.10

### Additional Information

Printing Java version, if the Java version doesn't show below, your Java path is incorrect
/home/name/.var/app/com.atlauncher.ATLauncher/data/servers/vanillaplus/LaunchServer.sh: line 27: java: command not found

Launching fabric-server-launch.jar with '2G' max memory, jvm args '' and arguments ''
/home/name/.var/app/com.atlauncher.ATLauncher/data/servers/vanillaplus/LaunchServer.sh: line 32: java: command not found
Press any key to close...

(I changed the user name to name because it had my real name)

**Comment by axtloss** [comment]
This is not an issue with apx, flatpaks cannot access system things. This issue should be reported in the atlauncher flathub repo.
