### ISSUE TITLE
flathub vaults not encypting

### ISSUE THREAD

**Issue by kalewheat042** [Vanilla-OS/iso-builder#195]
### Issue Description

i went to use vaults from flat hub and i installed CryFS and every time i made a vault it would give some weird error, so i decided to use  gocyptfs and it makes the vault with no errors however when i lock the vault i can still access it via the mount location. meaning it for some reason never closes the folder or encrypts it.  

### Steps to Reproduce

1.open vaults use gocyptfs
2.type in password for vault
3.choose directory of vault 
4.make vault
5.unlock vault
6.place file inside
7.close vault 
8.go to mount directory 
9.open file thats supposed to be encrypted?

https://github.com/Vanilla-OS/os/assets/109868025/c4f221b6-8938-470a-8d33-e04f1e767f54

### On what version of Vanilla OS this happens?

22.10

### Additional Information

hopefully i found the right place to report this bug, if not then please help me find the right place. if that is infact the vaults git-hub page.

also thank for making such a good os. other than vaults its been a dream to use, keep up the good work!!

**Comment by axtloss** [comment]
How did you install CryFS? And did gocryptfs work in other distros

**Comment by kalewheat042** [comment]
i installed CyFS on --DNF and gocyptfs on the --AUR and in a Ubuntu virtual machine gocypts does work and lock.

**Comment by axtloss** [comment]
Yeah that's the issue then, CryFS/gocryptfs have to be on the host, so either use `--nix` or abroot directly (nix is preferred)

**Comment by kalewheat042** [comment]
Okay thanks, ill close, thanks for helping.
