### ISSUE TITLE
Can't set up a custom default browser

### ISSUE THREAD

**Issue by Tatuck** [Vanilla-OS/iso-builder#199]
### Issue Description

Hello! I have installed Google Chrome on VanillaOS but if I try to change the default browser in settings it doesn't show up.
I have encountered another issue while installing Chrome, I don't know if it is related to this, but I think you should check it: #https://github.com/Vanilla-OS/apx/issues/231
![image](https://github.com/Vanilla-OS/os/assets/59171409/fe9634f0-48ed-4cb0-803a-dcdc482e424f)

### Steps to Reproduce

- Download .deb file from chrome's official website
- Install it with: `apx install --sideload google-chrome-stable_current_amd64.deb`
- Extract the .desktop: `apx export google-chrome-stable`
- Open settings -> Default Applications
- Check Web

### On what version of Vanilla OS this happens?

22.10

**Comment by axtloss** [comment]
Use flatpak (the software store) to install chrome, you'll be able to set it as the default browser.

**Comment by Tatuck** [comment]
> Use flatpak (the software store) to install chrome, you'll be able to set it as the default browser.

Thanks for your reply, but is it any other way I can do it installing like I did? I prefer using the original source as in the software store it shows chrome with a 0 star review and unsafe.

**Comment by axtloss** [comment]
The one in the software store is the official source, it uses the same deb that you installed.

The reason why it's shown as "unsafe" is because it still uses x11, which the one you installed with apx does too, they are identical.

**Comment by Tatuck** [comment]
Oh I didn't know that. Thank you for your help. But just for knowledge, is
it possible to do it the way I did it? Also, could you check the issue I
mentioned? Thank you!

**Comment by axtloss** [comment]
Yes it probably is possible in some way, but I do not know how.

**Comment by Tatuck** [comment]
Ok, thank you so much for your help!
