### ISSUE TITLE
No extension support!

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#20]
I have tired to install extensions from the extensions app, but since the GNOME version is '43.0' (remember the .0) and extensions say '43', they  do not match, thus being unsupported. And yes, i am on Wayland
<br>
## My Specs and Settings
![Screenshot from 2022-11-20 20-07-54](https://user-images.githubusercontent.com/100056951/202923748-47dc4a76-fa65-47cc-b37e-daf5fd321231.png)
<br>
## Extensions
![Screenshot from 2022-11-20 20-03-54](https://user-images.githubusercontent.com/100056951/202923597-6feccd27-8411-4fce-831c-6d905c2b2b0d.png)
![Screenshot from 2022-11-20 20-05-19](https://user-images.githubusercontent.com/100056951/202923658-146ac2fe-8af0-4878-ae11-6acd403b0014.png)
![Screenshot from 2022-11-20 20-06-14](https://user-images.githubusercontent.com/100056951/202923692-82731f65-e742-48d2-8547-569d0dc2e0ca.png)
![Screenshot from 2022-11-20 20-11-29](https://user-images.githubusercontent.com/100056951/202923880-f324bf30-98c8-42ff-aa0e-20c083408993.png)

**Comment by Teh404Gal** [comment]
Alot of people including me have had this error, its tracked in a private repo
Weird that it used to actually say null instead of 43.0

**Comment by mirkobrombin** [comment]
Fixed in next release which will be distributed soon
