### ISSUE TITLE
Can't set up vanilla OS! Incredibly glitchy gui

### ISSUE THREAD

**Issue by Dandandooo** [Vanilla-OS/iso-builder#201]
### Issue Description

The screen is flashing between modes and shades, GUI is disappearing, and it happens every time I boot up vanilla os.

### Steps to Reproduce

Start vanilla OS and run first setup

I don't know if it matters or not, but my bios has been set up to be able to run windows 11 (so secure boot etc.)

### On what version of Vanilla OS this happens?

22.10

### Additional Information

I have a video here: [https://share.icloud.com/](https://share.icloud.com/photos/033w1-pcZ-HsOoExqORP5GlcA)

**Comment by mirkobrombin** [comment]
Closing as per no many details to debug.
