### ISSUE TITLE
Three finger gesture not working after finilization

### ISSUE THREAD

**Issue by WiredMic** [Vanilla-OS/iso-builder#204]
### Issue Description

I cannot use three finger gestures to move around on the desktop. The gestures did not work when booted from a USB. However, they worked before the intallation was finialized. After the reboot at the end of the installation they stopped workning.

### Steps to Reproduce

Try to install Vanillia OS on a laptop with a trackpad.

### On what version of Vanilla OS this happens?

22.10

### Additional Information

I have a lenovo legion laptop. Model number Y530-15ICH-1060.

It runs nvidia.

I tried Vanilla OS version 22.10

**Comment by pulkitkrishna00** [comment]
The live boot has X11 by default. And X11 is used by default if it detects Nvidia. Gestures don't work on X11. You can log in to wayland session from the login screen using the cog icon in the bottom right corner. Gestures work on wayland.
