### ISSUE TITLE
Upgrade kernel to 6.0

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/iso-builder#21]

**Comment by cooligula** [comment]
This should be high priority, since it is preventing 11th and 12th gen Intel processors from using Vanilla OS.

**Comment by kbdharun** [comment]
> This should be high priority, since it is preventing 11th and 12th gen Intel processors from using Vanilla OS.

Agreed, we will figure out a way to custom-sign kernels soon, for a brief release during a specific release candidate we had this but due to signing issues with secure boot we postponed it to after stable.

**Comment by sbe-arg** [comment]
Some form of quick command upgrading at user risk from mainline could do... signature only needed for nvidia drivers and secure boot
 https://kernel.ubuntu.com/~kernel-ppa/mainline/?C=N;O=D

**Comment by sbe-arg** [comment]
Just tested this and works fine https://github.com/bkw777/mainline

**Comment by mirkobrombin** [comment]
Internally tracking new kernel signing.

**Comment by xplosionmind** [comment]
> Internally tracking new kernel signing.

Hi, sorry for the probably dumb question, but what does this mean?

**Comment by mirkobrombin** [comment]
Means that we are managing to build our own Linux kernel and signing it to allow the secure boot

**Comment by xplosionmind** [comment]
Oh, I see. Thanks for the explanation!

Still, do you have any useful articles I could read or tutorials I can watch in order to understand this concept? I do not really understand why the default Linux kernel would not permit secure boot.
