### ISSUE TITLE
Files from Kindle Fire are not showing up but my phone is.  (Android Devices)

### ISSUE THREAD

**Issue by Barrettloganj13** [Vanilla-OS/iso-builder#211]
### Issue Description

When I connect my Kindle Fire tablet (Fire OS 7 Android 9)  to my computer using MTP mode it doesn't show my files when the tablet is unlocked.  My phone which is a Samsung Galaxy S21 FE running Android as well is not having the same problem using MTP.

### Steps to Reproduce

- Connect a Kindle Fire tablet to computer
- Unlock tablet
- Make sure that the tablet is in MTP mode
- open Files
- Select the tablet
- Try to browse through the Tablet Files

### On what version of Vanilla OS this happens?

22.10

### Additional Information

What should show up is internal storage but it is nothing instead.

**Comment by Barrettloganj13** [comment]
Fire OS is Based off of the Android Open Source Project Operating System Code

**Comment by kbdharun** [comment]
Hi, Thanks for reporting this issue. Unfortunately, there isn't a proper (and actively maintained) package we can include in the host for MTP support (there are `mtpfs` and `jmtpfs` for FUSE but they haven't been updated in a while and also have a lot of issues with devices), so I am closing this issue as not planned.

There is an alternative GUI (which is a dedicated application and doesn't integrate with Files) called [`gmtp`](https://packages.vanillaos.org/package/gmtp) which could work with your device. You can install it in Kinetic with `sudo abroot exec apt install gmtp` (then reboot) and in Orchid with:

```bash
pkexec abroot pkg add gmtp
pkexec abroot pkg apply
```

**Note**: This will add the package to your system via a local image
