### ISSUE TITLE
Build script doesn't handle dpkg configuration file question

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/iso-builder#214]
### Issue Description

When a package comes with a default configuration file, yet there is already a custom one present in the system, `dpkg` asks how to resolve this conflict. By default it will keep the one already in system — this might be a problem on its own, depending on what you want to happen. The other issue is that the build fails on such question with the following error:
```
end of file on stdin at conffile prompt
```

### Steps to Reproduce

- be on commit 7f7cd33
- run the docker command from README to build it
- see the issue, if it's present

I'm not sure why I have the configuration mismatch, but not GH actions two weeks ago — the version of affected package is the same in both logs. 

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

```
Preparing to unpack .../archives/adduser_3.132_all.deb ...
adduser.conf with unknown checksum (probably locally changed) encountered. You can continue after answering the dpkg configuration file question.
Unpacking adduser (3.132) over (3.121ubuntu1) ...
Setting up adduser (3.132) ...

Configuration file '/etc/adduser.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** adduser.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package adduser (--configure):
 end of file on stdin at conffile prompt
Errors were encountered while processing:
 adduser
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...

```

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.

--

PS. there were major changes in the live-iso, probably that's fixed already.
