### ISSUE TITLE
apx install <...>   --->  dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. DPKG not found

### ISSUE THREAD

**Issue by Bayanda62** [Vanilla-OS/iso-builder#215]
### Issue Description

apx install <...>   --->  dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
i ran the abouve command and got ->
 "
DPKG not found"

Now I cant install , or upgrade

### Steps to Reproduce

maybe it was a slow internet connection

### On what version of Vanilla OS this happens?

22.10

**Comment by Thenathayalan** [comment]
In vanilla os control center go to subsystem in which open terminal for sub system apx_managed and run sudo dpkg --configure -a and now it fixed
