### ISSUE TITLE
Error on "apx export --bin <bin-name>

### ISSUE THREAD

**Issue by Bayanda62** [Vanilla-OS/iso-builder#216]
### Issue Description

i ran the command "apx export --bin nvim"
and got this, Seems like something broke

Could not read directory /usr/bin/python3: readdirent /usr/bin/python3: not a directory

### Steps to Reproduce

apx export --bin <bin-name>

### On what version of Vanilla OS this happens?

22.10

**Comment by arejula27** [comment]
I got the following error:
```bash
$ apx export  --bin vim
  ERROR   Error exporting binary: Failed to execute printenv: exit status 1
Error: Failed to execute printenv: exit status 1
Usage:
  apx.use export <application/binary> [flags]

Examples:
apx export htop
apx export --bin fzf

Flags:
      --bin           export.binFlag
      --apt           flags.apt
      --aur           flags.aur
      --dnf           flags.dnf
      --apk           flags.apk
      --zypper        flags.zypper
      --xbps          flags.xbps
      --nix           flags.nix
  -n, --name string   flags.name
  -h, --help          help for export

Global Flags:
  -v, --verbose   apx.verboseFlag

  ERROR   Failed to execute printenv: exit status 1

```

**Comment by mirkobrombin** [comment]
Looks like you are missing the package manager, to export you must provide `--apt or --dnf etc..` otherwise apx does not understand from where to export the binary.
