### ISSUE TITLE
Missing vanilla_keyring.gpg when building Orchid ISO

### ISSUE THREAD

**Issue by mrusso99** [Vanilla-OS/iso-builder#219]
### Issue Description

As the title implies, when i try to build the os ISO using the command 
```
docker run --privileged -i -v /proc:/proc \
    -v ${PWD}:/working_dir \
    -w /working_dir \
    debian:sid \
    /bin/bash -s etc/terraform.conf < build.sh
```

I get the following error

```
#------------------#
# LIVE-BUILD BUILD #
#------------------#

[2023-08-17 23:01:09] lb build 
P: live-build 20230502
P: Building for a debian/sid/amd64 system
[2023-08-17 23:01:09] lb bootstrap 
P: Setting up clean exit handler
[2023-08-17 23:01:09] lb bootstrap_cache restore
[2023-08-17 23:01:09] lb bootstrap_debootstrap 
P: Begin bootstrapping system...
P: If the following stage fails, the most likely cause of the problem is with your mirror configuration or a caching proxy.
P: Running debootstrap...
E: specified keyring file (/usr/share/keyrings/vanilla_keyring.gpg) not found
```

### Steps to Reproduce

- Clone the repository
- Execute the command ```docker run --privileged -i -v /proc:/proc \
    -v ${PWD}:/working_dir \
    -w /working_dir \
    debian:sid \
    /bin/bash -s etc/terraform.conf < build.sh```

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
Please do not build from scratch, download a ISO from the actions view We do not provide support for such case.

Anyway, the file is present ad https://github.com/Vanilla-OS/os/blob/orchid/etc/config/includes.chroot/usr/share/keyrings/vanilla_keyring.gpg
