### ISSUE TITLE
Feature Reuqest - tar file for wsl

### ISSUE THREAD

**Issue by mateowoetam** [Vanilla-OS/iso-builder#22]
I want to be able to use this in the recently out-of-beta Windows Subsystem for Linux.

**Comment by Teh404Gal** [comment]
Wsl isnt really meant for desktop centric oses like vanilla
And kind of feels weird to have 2 layers of containers
When 1 is only required

**Comment by kbdharun** [comment]
> Wsl isn't really meant for desktop-centric oses like vanilla And it kind of feels weird to have 2 layers of containers When 1 is only required

This 

@Mathew420w0 you can create VM in Virtualbox or VMWare workstation or even in HyperV (not sure) to test out Vanilla OS.

**Comment by mirkobrombin** [comment]
I'm not planning to support WSL since none of the core-features of Vanilla works on it. Thanks for your feedback :)
