### ISSUE TITLE
Can't Share Screen On Discord

### ISSUE THREAD

**Issue by MertKalkanci** [Vanilla-OS/iso-builder#220]
### Issue Description

Installed discord from flatpak
using nvidia server 535 driver
gtx 1650 4GB graphics card

### Steps to Reproduce

-Install discord from flatpak
-install nviida 535 server driver
-try to share screen

### On what version of Vanilla OS this happens?

22.10

**Comment by MertKalkanci** [comment]
Also it was working nice on ubuntu 20.04 LTS

**Comment by axtloss** [comment]
This is not a vanillaos issue. It's an issue with discord not supporting Linux properly
