### ISSUE TITLE
grub-install: error

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#222]
### Issue Description

I tried to install Orchid on VM but it failed with this error : 
```
grub-install: error: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify -- traget or --directory
panic: Failed to run grub-install: exit status 1

goroutine 1 [running]:
main.main()
	github.com/vanilla-os/albius/albius.go:37 +0xeb
```

### Steps to Reproduce

- boot a vm with alpha orchid iso
- launch the install on full encryption disk
- error

tried 2 times

### On what version of Vanilla OS this happens?

Unreleased

**Comment by kbdharun** [comment]
Hi, Thanks for opening the issue. Vanilla OS only supports UEFI (and doesn't support Legacy Boot). You need to select UEFI/EFI during the VMs creation.

**Comment by Thatoo** [comment]
Installation suceeded indeed
