### ISSUE TITLE
[Orchid] French Macintosh keyboard layout isn't ok

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#223]
### Issue Description

Like in most debian install, @ and < are reversed

### Steps to Reproduce

when setting the keyboard during install time, I test the layout and found out that @ and < are reversed

### On what version of Vanilla OS this happens?

Unreleased

**Comment by kbdharun** [comment]
Hi, Unfortunately, this issue is outside our scope as we don't repackage any keyboard layouts and directly use the Debian ones. I would suggest reporting this issue upstream if not already done.
