### ISSUE TITLE
[Orchid] Translation is weird

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#227]
### Issue Description

Gnome works perfectly with french language usually but Vanilla OS has some problem.
![image](https://github.com/Vanilla-OS/live-iso/assets/464782/9569df15-9168-4b1b-9cd3-1002fc4c7f4d)

Only the app name is translated. "Activities" is english, The date is in english, "Type to search" is also english

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/11d31681-0c4f-4b19-a3bf-dabfb145fb38)

In here, "Activities" is still english but "Paramètres" is french.  "Settings" is neglish but "Réseau", "Apparence", "Recherche", "Partage" are in french but on last panel "Network" and "Connected" and "Not set up" are again english.

### Steps to Reproduce

- Choose french language at install
- wait for install to finish and reboot
- weird french translation

### On what version of Vanilla OS this happens?

Unreleased

**Comment by Thatoo** [comment]
A great improvement has been made on the #77	17/09/2023 version!

I'll list here all I could find, and that's not much really, you seriously rock to manage such huge improvement in such short time : 

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/1579a656-26ec-4db4-bdc1-7a76bb7c213a)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/a32b5d0f-6fd5-48ae-b525-98dcc372e5b1)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/df7b5984-d279-4e8a-9f9c-e36ec17f8fc7)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/ae14f2ad-d01c-45f0-8fad-cb2839047603)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/f9efcc0f-5115-4c29-865d-85f72e115b5e)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/bc3594e6-5817-4c1b-837b-8f307c222484)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/79cb4122-804f-4f1e-a607-335bd2ea69c4)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/8509e484-21fe-4949-8b2c-51ad51ae1c8d)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/59b0d3e4-b5f7-4ffa-998e-a81a3fed0af1)

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/34592ae4-bc47-48da-881b-1d51d99f9781)

**Comment by kbdharun** [comment]
Thanks for reporting this issue. We don't handle non-component translations and instead use the upstream ones from Debian Sid (which follows GNOME's strings). 

In this case, the GNOME Control Center (Settings) was ported to use the new libadwaita widgets in GTK4 with changes to the strings overall so there is a chance that the newer strings haven't made it into the Debian package yet (let me know if it is the same now in the current builds) or else I would suggest waiting for some time till Stable before reopening this issue.

Edit. The updated strings in the Control Center got merged just a week ago https://gitlab.gnome.org/GNOME/gnome-control-center/-/commits/main/po/fr.po, so it would definitely take some time to land to the end user.
