### ISSUE TITLE
[Orchid] nothing got installed after launch settings

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#228]
### Issue Description

After the first reboot, we are asked to set a user and select some packages we want.
I selected to install all but none got installed, not core, not office and not the third one neither...

### Steps to Reproduce

-  Finish the install
- reboot
- first start
- ask for some question like user and what packages we want to install
- select to install all
- reboot again
- login with your user
- nothing has been installed

### On what version of Vanilla OS this happens?

Unreleased

**Comment by Anik-kun** [comment]
+ I have the same problem
VanillaOS-22.10-all.20230226 (22.10-r8)
![er_First_Install_2023-09-21](https://github.com/Vanilla-OS/live-iso/assets/88995093/5de52777-2fcd-422d-b4bc-d567ef689539)

**Comment by themattgillam** [comment]
Same issue on 22.10-r8 & 22.10r7. Seeing several "Failing to fetch" errors for Ubuntu packages when running the first setup.

**Comment by mirkobrombin** [comment]
This was fixed in latest 22.10 build.
