### ISSUE TITLE
Allow offline installation 

### ISSUE THREAD

**Issue by mttbx** [Vanilla-OS/iso-builder#230]
### Feature Description

Can we install this os without network?

### Rationale

Sometimes network is unavailable

**Comment by mttbx** [comment]
I think this feature is important. Currently I install vanilla os on vm. And I set up proxy in the host so that I can install it. But I can't do that easily if I want to install vanilla os in a real machine. Most distributions have offline iso too. I comment this issue again so you can know this potential need.

**Comment by Thatoo** [comment]
@mirkobrombin can we close this in favor of https://github.com/Vanilla-OS/live-iso/issues/301 ?
