### ISSUE TITLE
Vanilla 2 Testing Grub Issue

### ISSUE THREAD

**Issue by davidganz** [Vanilla-OS/iso-builder#235]
### Issue Description

Hi!
During Grub installation Error: grub-install error /usr/lib/grub/i386-pc/modinfo.sh doesn't exist
Easily you are missing the  **grub-pc Package** in the Setup.
See my Post here: [https://tutorialforlinux.com/2023/09/10/debian-grub-install-error-usr-lib-grub-i386-pc-modinfo-sh-doesnt-exist-troubleshooting-guide/](url)

### Steps to Reproduce

Try installing it in a VirtualBox VM.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by axtloss** [comment]
Vanilla OS orchid does not support legacy boot. You have to set your VM to use uefi instead
