### ISSUE TITLE
[Orchid] Finalizing is arriving very late

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#237]
### Issue Description

After installation of Orchid and login with a username, the user can't do much before the "finalizing" step is completed.
However, the finalizing screen is taking way too long to be displayed. The user might switch off the computer before it arise.

### Steps to Reproduce

- install orchid
- restart
- setup user on first boot
- restart
- login
- nothing to do before the finalizing screen popup (take very long time, about 5 minutes).

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
