### ISSUE TITLE
[Orchid] impossible to update vanilla-backgrounds

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#238]
### Issue Description

Update vanilla-backgrounds to v 1.0.4 is not happening after reboot.

### Steps to Reproduce

- Install Orchid `v #77	17/09/2023 `
- Update thanks to the Softwares app
- Ask for reboot
- reboot
- one update is still available, vanilla-backgrounds to v 1.0.4
- update
- reboot
- boot issue
- reboot
- one update is still available, vanilla-backgrounds to v 1.0.4
- can be repeated over and over

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
The gnome software package got updated without our patch. I'll fix soon
