### ISSUE TITLE
Something went wrong during installation of latest build #79

### ISSUE THREAD

**Issue by jsarkari** [Vanilla-OS/iso-builder#240]
### Issue Description

So I was going through the installation process on Linux GNome Boxes and it failed after the Encryption page it started installing then a few minutes later or so it failed.

After copying all the blobs

This is the log afterwards:

gru-install: error: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or -- directory.
panic: Failed to run grub-install: exit status 1

goroutine 1 [ running ] :+1:
main.main()
                 github.com/vanilla-os/albius/albius.go:37 +0xeb

### Steps to Reproduce

- Download and extract #79 build
- Open Gnome Boxes
- Install ISO downloaded
- Proceed through initial installation pages
- Enter a strong password for the Encryption
- Let it start installing
- Then it failed with the information as listed in the description...

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

OS Version: Vanilla OS 2 Orchid
#79

**Comment by mirkobrombin** [comment]
What's build id is this?

**Comment by jsarkari** [comment]
Its the Alpha build 
OS Version: Vanilla OS 2 Orchid released yesterday #79
VanillaOS-2-testing
I cannot see the build in Settings, About etc as its still installing

**Comment by jsarkari** [comment]
I have gone into the boot menu and chose option 3 to get back into the OS, hopefully it will resume the installation which it has. I will see if I get the same error again.

**Comment by jsarkari** [comment]
It is at the Copying blob stages and its taking a long time during this process as 8 blobs are being copied at once, my host laptop is a Tuxedo laptop with 32 GB RAM and 2 x 2 TB hard drives and a i9 Intel 13th Gen CP, not sure why this bit is so slow?

**Comment by jsarkari** [comment]
So it failed again and I noticed in the log that it is showing the same blob 9 times at least and then saying already exists. Is this why its taking so long as it is repeating the same process for the same blob. eg 4f4fb700ef54

**Comment by jsarkari** [comment]
As github is really slow at getting the blobs during the installation, is it therefore possible to include these in the iso? For me the iso downloaded in a few minutes on a wired network over 100 mbps. This would then eliminate the need and hopefully speed up the process during installing the software on a VM etc

**Comment by jsarkari** [comment]
So I realised that it was failing to install all the blobs from Github due to lack of disk space on the host machine, so I have managed to download all the blobs and get further into the installation of the alpha build.

But now it failed on the following>

grub-install: error: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or -- directory.
panic: Failed to run grub-install: exit status 1

goroutine 1 [running]:
main.main()
                 github.com/vanilla-os/albius.go:37 +0xeb

**Comment by cnd4** [comment]
Hello, it seems I have the same issue with latest alpha (downloaded from here: https://github.com/Vanilla-OS/live-iso/actions/runs/6454386217) when installing on Gnome Machines.

![Screenshot of the error](https://github.com/Vanilla-OS/live-iso/assets/6230696/0dd7bdf1-7695-4f1e-a96a-864db9650a12)

**Comment by axtloss** [comment]
Orchid only supports UEFI, you have to set your VM to use UEFI, not legacy bios.

**Comment by karwrkinga1** [comment]
MY BIOS IS ON UEFI, SECURE BOOT IS DISABLED, BUT I STILL HAVING THIS ISSUE.

I WAS USING THIS https://download.vanillaos.org/latest.zip

**Comment by axtloss** [comment]
Open a new issue and show the log
and dont write in all caps, you're not going to achieve anything with that

**Comment by karwrkinga1** [comment]
![image](https://github.com/user-attachments/assets/f0b02776-fc42-444d-9e81-b5202d6a80d0)
exactly the same as this image.

capitals are not typed on purpose

**Comment by axtloss** [comment]
If you get this error, then its not running with uefi

**Comment by karwrkinga1** [comment]
![image](https://github.com/user-attachments/assets/ebb76bf9-13b8-4ae9-b562-f520806e6ea8)
is that wrong place to check?

**Comment by axtloss** [comment]
Your system doesnt have to be uefi, the vm has to be

**Comment by karwrkinga1** [comment]
im trying to install on my system not on a vm

**Comment by axtloss** [comment]
then you arent booting the insatller iso through uefi

**Comment by axtloss** [comment]
you can try the iso from here <https://github.com/Vanilla-OS/installer-image/actions/runs/10546786380>, it only supports uefi so you shouldn't get that issue

**Comment by karwrkinga1** [comment]
![WhatsApp Image 2024-08-27 at 10 07 47_1027218f](https://github.com/user-attachments/assets/8ba45fe4-136f-4dd0-be9e-9f8d67e327b3)

new error//
