### ISSUE TITLE
[Orchid] Nothing happen after finalizing installation

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#243]
### Issue Description

I install  #79 | 20/09/2023 build of Vanilla. Reboot. Create user. Reboot Wait for finalizing the installation. Reboot. Vanilla OS is empty and invite me to finalize again the installation...

### Steps to Reproduce

see above

### On what version of Vanilla OS this happens?

Unreleased

**Comment by escomz** [comment]
The same problem when i try to install.

**Comment by Thatoo** [comment]
After installation of # 82 I got the same issue but I decline the second  "finalizing the installation" and I then was invited to reboot to install updates.
Then after reboot, I was required my password to install some stuff, that's not really clear... Plus it's a third step before being able to use the computer, it makes it a lot. And after that still I couldn't use it before rebooting again.

After rebooting, the list of users is really long to come, not always coming, sometime I have to type my username.

And still, after rebooting, I can't do much but watch the wallpaper and go into settings.

**Comment by lightsabata** [comment]
Exact same behavior for me on 82:
After final wizard installation, rebooted, then ask login with username, after login it ask for update and reopen the final wizard installation at the same time.
Cannot do anything else other than complete again final wizard and stuck in that loop.

**Comment by Thatoo** [comment]
I faced again this same exact issue with #84 . 
After final wizard installation, rebooted, then ask login with username, after login it ask for update and reopen the final wizard installation at the same time.
I declined and logout/login and again it requested to  "finalize the installation".
I declined again and reboot. It asks to install more updates and I let it tick. Double reboot to, I guess, install updates.
Login.
Stuck in the loop.

**Comment by nisel11** [comment]
If you go to tty3(Ctrl+Alt+F3), you can close Gnome(killall gnome-shell) and run the normal version via gnome-shell --wayland --mode=user. I don't know how to remove the gdm session file that makes the startup go to the first-setup environment
After restarting when entering the password I got a gear in the bottom right corner where I selected Gnome, after that it was fine, you can try killing and running gdm to make it appear

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
