### ISSUE TITLE
Unable to boot USB with a Macbook Air 2017

### ISSUE THREAD

**Issue by ferranrego** [Vanilla-OS/iso-builder#245]
### Issue Description

I'm trying to install VanillaOS 2 orchid BUILD 79 to test it with a Macbook Air 2017 (In which I already installed successfully the old version of VanillaOS) but I got the following error:

![image](https://github.com/Vanilla-OS/live-iso/assets/3515290/ba8b7da8-a460-4e70-9acc-2532f7c809b5)

### Steps to Reproduce

- Use Unetbootin in to create a bootable USB
- Start Macbook Air (Power button) + ALT button
- Start Grub and select any of the booting options
- Vanilla OS logo with a loading wheel
- Error

### On what version of Vanilla OS this happens?

Unreleased

**Comment by castleknox** [comment]
I've attempted writing VanillaOS Orchid on multiple USB drives using multiple applications like Fedora media writer, Balena Etcher, etc. to no avail.

Really rather frustrating.
