### ISSUE TITLE
Something went wrong during install-Orchid#80

### ISSUE THREAD

**Issue by jsarkari** [Vanilla-OS/iso-builder#247]
### Issue Description

During install VanillaOS-2 (Vanilla OS 2 Orchid - Alpha builds) it failed with the following information in the log:

grub-install: error: /usr/lib/grub/i386-pc/modinfo.sh does't exist. PLease specify --target or --directory.
panic: Failed to run grub-install: exit status 1

goroutine 1 [running]:
main.main()
                 github.com/vanilla-os/albius/albius.go:37 +0xeb

### Steps to Reproduce

Install on VirtualBox
Turn on EFI (special oses)
Start
Waits at the grub menu 
Unable to start the OS
Turn off EFI (special oses)
Start
VanillaOS-2 starts
Goes through the initial setup, Region, keyboard etc
Then fails to complete during install as described above

### On what version of Vanilla OS this happens?

Unreleased

**Comment by jsarkari** [comment]
Another issue noted after starting:
As there is no menu shown as it didn't fully install
Right mouse on desktop
Select Display Settings
After about 30 seconds
Install wizard appears

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
