### ISSUE TITLE
File selector cut off on Firefox (Flatpak)

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#251]
### Issue Description

File selector is cut off on Firefox using the flatpak version 

### Steps to Reproduce

- Use Firefox flatpak
- Upload a file 

### On what version of Vanilla OS this happens?

22.10

### Additional Information

![image](https://github.com/Vanilla-OS/live-iso/assets/122128828/a2acbed8-6747-4839-8e54-1fd01c374d00)

**Comment by mirkobrombin** [comment]
Hi, this kind of problems must be reported to GNOME directly https://gitlab.gnome.org/GNOME
