### ISSUE TITLE
Vanilla OS 2 Orchid - Alpha #82 on VirtualBox after setup keeps returning to setup screen at start/reboot

### ISSUE THREAD

**Issue by jsarkari** [Vanilla-OS/iso-builder#253]
### Issue Description

As per previous builds even when I managed to get this OS up and running albeit only on VirtualBox for now, on reboot or start thereafter from initial setup, you are faced with the setup of having to re-enter the country, keyboard, name etc again and again on each start.

In VirtualBox I have the following settings:

Base Memory: 4096 MB / 4 GB
Enable EFI (special OSes only): On / If not set on then it fails to boot.
Processors: 4 CPUs
Execution Cap: 100%
Video Memory: 128 MB
Graphics Controllor: VMSVGA
3D Acceleration: Off
Storage: SATA Port 0 - 100 GB

Also there is no menu or dashboard display and it is not full screen.

So you never get to the end point.

Again first tested on Boxes and the setup fails to finish as per previous few Alpha builds I have tested. So not even to the point of being able to enter the name, password etc.

### Steps to Reproduce

- Install Alpha build #82 with settings as listed in the Issue Description
- Start
- Go through initial setup
- Let it reboot
- Enter your credentials etc
- Reboot
- On start the setup screen appear awaiting for you to go through the 2nd stage of setup credentials etc.
- Restart after shutdown same screen appears
- No full screen even after maximising VBox
- No menu displayed on the centre time/date and the right menu

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

Build: #82

**Comment by jsarkari** [comment]
Retested after turning off EFI then going through setup of 2nd stage, language etc and it fails like on Boxes, in log:

Locking /usr/bin/dkpg - trigger
panic: interface conversion: interface {} is nil, not string....

![Screenshot_20231018_123509](https://github.com/Vanilla-OS/live-iso/assets/18397011/46a3bf4e-2b03-4454-bdae-74fcfe34e25c)

**Comment by Juliandev02** [comment]
I have heard this problem from several people, and for me the following method works: 

After you have gone through the First Setup process the first time, reboot your system normally. After you have rebooted, please **do not log in** directly. You just click on your username and then on the gear wheel/settings icon at the bottom right where you can select the desktop. There you select GNOME. And then you can log in
![image](https://github.com/Vanilla-OS/live-iso/assets/81520713/eae1fb0f-9385-486b-9d82-3a1550ee81c9)
I hope this helps.

**Comment by jsarkari** [comment]
For me it was after the 2nd process where you enter your name, password, device name, what you want to install then reboot then it knows what your user credentials are and as you suggest select username then choose GNOME.

Would be interesting to know what the default was it wasn't indicated.

But finally after many weeks of trying to get either an Alpha or prod build to fully installed, it worked!

Thanks for the tips!

**Comment by mttbx** [comment]
@jsarkari Got the same bug: 
panic: interface conversion: interface {} is nil, not string
Must be efi boot

**Comment by taukakao** [comment]
This will probably be fixed by https://github.com/Vanilla-OS/first-setup/pull/233

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
