### ISSUE TITLE
Vanilla OS 2 Orchid - Alpha #82 on VirtualBox after downloading updates and rebooting twice the updates are still there

### ISSUE THREAD

**Issue by jsarkari** [Vanilla-OS/iso-builder#254]
### Issue Description

So I have finally managed to install this alpha build by switching to GNOME the first option after 2nd install process.

But I have this installed on VBox and with encryption.

I tested the updates and there was a system update and then some application updates.

The application updates download and install fine, but after restarting with a note that the system updates will be installed.

After this process and going back the grub twice so having to enter the encryption password twice prior to logging in. When I went to restart again the updates are still there waiting to be installed again, so something is not working on System Updates in this current build #82.

### Steps to Reproduce

-Check for updates in Software
-Download and install and application updates
-Restart so that it can install the updates
-With encryption on 
-Enter encryption password
-It will restart back into the grub again
-Enter encryption password again
-Enter credential password
-once at the desktop
-Restart and see if the updates are waiting to be installed again

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

I have gone through this process several times with the same results.

I doubt the encryption is causing issues but you never know.

Just not sure why I have to enter the encryption password twice as it is returning back to the grub menu.

The only thing is during installation there is now 2 roots something must have happened so I am on the AB  root B now.

**Comment by me-self** [comment]
This seems quite similar to what I reported in the ABRoot repo. I think I should close [mine](https://github.com/Vanilla-OS/ABRoot/issues/144)
Also, I can confirm it's still an issue without encryption.

**Comment by mirkobrombin** [comment]
Updates you see in GNOME Software are not managed by ABRoot so they will never apply. We are working to patch GNOME Software for that.
