### ISSUE TITLE
Unable to play audio output through montor or external tv even when the host is selected for it

### ISSUE THREAD

**Issue by jsarkari** [Vanilla-OS/iso-builder#255]
### Issue Description

I can only play audio via laptop speakers as the hdmi output is not listed only analog output / with or without the amplified in Settings Sound Output.

I have installed on Vbox and using Vanilla OS 2 Orchid alpha build #82.

I have tried native internet and also Shortwave same results for both.

### Steps to Reproduce

- Connect to a 2nd monitor
- Play audio via web or shortwave etc.
- Listen via laptop speakers
- Settings - Sound - Output
- See if there is an option in the Output Device for HDMI output
- Nothing listed

### On what version of Vanilla OS this happens?

22.10

### Additional Information

I have also tried to switch the host laptop output from laptop speakers to hdmi but that makes no difference.

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
