### ISSUE TITLE
NTP is not configured on live iso

### ISSUE THREAD

**Issue by rohmishra** [Vanilla-OS/iso-builder#256]
### Issue Description

- NTP is not actually configured for live ISO
- timedatectl show-timesync says no route to host. timedatectl timesysmc-status says org.freedesktop.timesync1 was not provided by any service files.
- This causes netowork check to fail as certificate on vanillaos.org may have been issued after the current system date time\
- There is no indication that date time sync via NTP may be not working in UI. 

### Steps to Reproduce

- use a system with out of date local time

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
