### ISSUE TITLE
Failed to get revokefs-fuse socket from system-helper: User _flatpak does not exist in password file entry

### ISSUE THREAD

**Issue by mttbx** [Vanilla-OS/iso-builder#261]
### Issue Description

`Failed to get revokefs-fuse socket from system-helper: User _flatpak does not exist in password file entry`
I don't know if this is a bug in flatpak or vanilla os.

### Steps to Reproduce

flatpak install [any app]

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mttbx** [comment]
[flatpak 1.14](https://github.com/flatpak/flatpak/issues/2959)
Maybe upgrade flatpak to a new version?

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
