### ISSUE TITLE
Freezes in Orchid installer

### ISSUE THREAD

**Issue by jens-hj** [Vanilla-OS/iso-builder#264]
### Issue Description

Most of the time the installer freezes very shortly after connecting to a wifi network.
There is some variance to it, but most of the time as soon as I attempt clicking the right arrow to go to the next step after connecting to a network the installer is frozen, and nothing happens upon clicking the right arrow in the installer.

If it doesn't freeze at that exact point, it will happen a briefly after.

I do end up getting through the whole installer, but since I have other issues too, I wonder if this can impact the first setup of the system. As described in [this issue](https://github.com/Vanilla-OS/first-setup/issues/228), I also experience trouble getting through the first-setup, and get stuck in a first-setup loop over and over.

### Steps to Reproduce

1. Flash the ISO onto a flash drive with Balena Etcher
2. Boot from the flash drive
3. Choose to install Vanilla OS
4. Start stepping through the installer
5. Freeze will occur
6. Log out of the system, for me it automatically logs me back in
7. Now I can step through the rest of the installer perfectly fine.

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

I am flashing with Balena Etcher from a Fedora 38 Workstation OS
The system is installed to an external M.2 NVMe SSD

Attempted with the latest Orchid ISO with ID #82 [https://github.com/Vanilla-OS/live-iso/actions/runs/6526023055](https://github.com/Vanilla-OS/live-iso/actions/runs/6526023055)

**Comment by me-self** [comment]
I believe this is the same issue as reported here: https://github.com/Vanilla-OS/vanilla-installer/issues/297
The testing I did before https://github.com/Vanilla-OS/vanilla-installer/issues/297 was closed would always result in this freeze. Ever since the issue has been closed, I've noticed the issue still remains, but only if the installer is already started when you connect to the network. If you'd like to install it now, you can rush to connect to a network through the top-right GNOME menu before the installer launches; alternatively you can let it freeze, kill the process when it prompts you to do so, and then launch the installer by clicking on the top-right GNOME menu, clicking the settings icon, navigating to the apps menu once the settings app has launched, then scroll down to the installer in the list of apps, click on that and launch it from there.

**Comment by tcmal** [comment]
Have just tried on bare metal with build 84 (which includes the mentioned fix for vanilla-installer), and I still get freezes. Sometimes I'm able to make it to the connectivity check panel, but it freezes there instead.

**Comment by tcmal** [comment]
Running with `VANILLA_SKIP_CONN_CHECK=1` only delays my issue, which suggests it may be a different freeze. Have tried replacing all the log levels in code with DEBUG, but still no helpful output.

**Comment by me-self** [comment]
> Have just tried on bare metal with build 84 (which includes the mentioned fix for vanilla-installer), and I still get freezes. Sometimes I'm able to make it to the connectivity check panel, but it freezes there instead.

Have you done this alone, or have you also tried one of the two options I mentioned (the second one is more reliable)? ever since the issue was closed it no longer crashes if you *already* have an active connection, but still if you are connecting while the installer is running.

**Comment by Shouri14** [comment]
> I believe this is the same issue as reported here: [Vanilla-OS/vanilla-installer#297](https://github.com/Vanilla-OS/vanilla-installer/issues/297) The testing I did before [Vanilla-OS/vanilla-installer#297](https://github.com/Vanilla-OS/vanilla-installer/issues/297) was closed would always result in this freeze. Ever since the issue has been closed, I've noticed the issue still remains, but only if the installer is already started when you connect to the network. If you'd like to install it now, you can rush to connect to a network through the top-right GNOME menu before the installer launches; alternatively you can let it freeze, kill the process when it prompts you to do so, and then launch the installer by clicking on the top-right GNOME menu, clicking the settings icon, navigating to the apps menu once the settings app has launched, then scroll down to the installer in the list of apps, click on that and launch it from there.

I tired both the methods mentioned, connecting to wifi before installer launches and killing the launcher, open it from settings... but I'm seeing the same issue. Installer freezes on the wifi page.

**Comment by me-self** [comment]
When killing and relaunching, you do connect to the wifi before relaunching?

**Comment by Shouri14** [comment]
> When killing and relaunching, you do connect to the wifi before relaunching?

Yes, few times it went to the next page but still hangs.

**Comment by me-self** [comment]
Hmmm... well then the issue I was experiencing may be different from yours...

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
