### ISSUE TITLE
get error when adding new subsystem in apx gui

### ISSUE THREAD

**Issue by mttbx** [Vanilla-OS/iso-builder#265]
### Issue Description

![截图 2023-11-13 15-07-08](https://github.com/Vanilla-OS/live-iso/assets/38148377/d6250f38-9c6f-49a5-bece-c70d40dfc1b8)

### Steps to Reproduce

1. open apx gui
2. add new subsystem and put a random name for it

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mttbx** [comment]
Note that the locale is not in US. This maybe the cause of the issue.

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
