### ISSUE TITLE
random files in home in container created by apx 

### ISSUE THREAD

**Issue by mttbx** [Vanilla-OS/iso-builder#266]
### Issue Description

![截图 2023-11-13 15-12-31](https://github.com/Vanilla-OS/live-iso/assets/38148377/d3d565ed-07e7-4dad-9a71-6c394d836dc0)
I think this is related to locale. The pic below is the terminal pic of vanilla-os:
![截图 2023-11-13 15-13-22](https://github.com/Vanilla-OS/live-iso/assets/38148377/4170ee36-6ba7-4c0b-9096-eb29e614d5f9)

### Steps to Reproduce

1. just enter random created container in apx
2. put ls to see the random file name

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
