### ISSUE TITLE
bash: distrobox: command not found

### ISSUE THREAD

**Issue by mttbx** [Vanilla-OS/iso-builder#267]
### Issue Description

I use the command as suggested by apx:
`distrobox enter apx-test5`
And I get the message:
`bash: distrobox: command not found`

### Steps to Reproduce

1. open a terminal
2. write command `distrobox enter apx-test5`

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
This is patched in Orchid (Vanilla OS 2), the problem is that apx is suggesting the wrong command, you have to use `apx` not `distrobox` since that's an internal command.

We have no effort to fix this in kinetic now, please just keep this in mind.
