### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by MiMillieuh** [Vanilla-OS/iso-builder#27]
Hello,

In the 29.11.22 build, the installer fails

It works on the 06.11.22 build.

Here som logs in the sceeenshots.

![20221130_010507.jpg](https://user-images.githubusercontent.com/52078885/204676369-095e49c0-89e4-441c-ae32-929e0f4707f6.jpg)
![20221130_010523.jpg](https://user-images.githubusercontent.com/52078885/204676374-701f9368-9828-4e80-b94b-cf0c6073a55f.jpg)

**Comment by pollux78** [comment]
Exact same issue happening on my main pc. Installed fine on my old laptop

**Comment by MiMillieuh** [comment]
It might be related to UEFI bios

**Comment by Zukureneno** [comment]
Got the same Error (installation via Gnome Boxes VM: Flatpak)

![image](https://user-images.githubusercontent.com/60487234/205153865-f2512362-129e-4bf5-be23-675a9e03ae98.png)
![image](https://user-images.githubusercontent.com/60487234/205154116-5dbba5b1-e499-43cf-94ef-6c25ba82dc88.png)
![image](https://user-images.githubusercontent.com/60487234/205154152-995eb121-85e4-47c8-a914-08c8190f308e.png)

**Comment by Teh404Gal** [comment]
From the log output it seems it succeeded to install, maybe gui got mistaken?
I remember this bug being patched 
This might be a regression

**Comment by MiMillieuh** [comment]
I think the installer is also maybe lacking a dependencie because the disk selection on that version allows only automatic installation and the older one allow also custom partitioning.

**Comment by Stefanious** [comment]
Seems as it doesn't finish grub install. Had to add it to grub manually to get it to boot.

**Comment by Speciolution** [comment]
Same here with the lates build December 17. (December 15 as well).

**Comment by Speciolution** [comment]
So it seems like the install actually worked. Vanilla OS just does not show up in the Grub menu and you gotta add it manually.

I did it like that:
Restart PC. Enter Bios/Uefi. Advanced settings and boot options. Add new Entry and choose the file Shimx64.efi. Save and Exit.

**Comment by mirkobrombin** [comment]
Fixed with latest build (less than 1h ago)
