### ISSUE TITLE
[Orchid] Panic: failed to unmount partition /dev/sda1 ; goroutine

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/iso-builder#271]
### Issue Description

Installation fails just after launching with this error log : 

![image](https://github.com/Vanilla-OS/live-iso/assets/464782/27701564-9035-41a0-9ce3-27d4e27f83a4)

### Steps to Reproduce

- Virtualbox - Debian - Linux x64 - EFI new VM with 40 Go of hdd and 4096 Mo of RAM
- Iso VanillaOS Orchid #89 is booting
- choose install
- check connection
- language
- keyboard
- hdd
- encrypt
- start installation
- fails immediately with the error log shown above

Tried three times.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by nisel11** [comment]
Try deleting one partition at a time via Gparted, it worked for me. But I'm having a different problem now with infinite initial setup. If you have a completely clean disk, I can't help in any way

**Comment by Thatoo** [comment]
How can I do that whereas VanillaOS has not yet been installed and the spacedisk of the VM is empty?

**Comment by Andrew-J-Larson** [comment]
> Try deleting one partition at a time via Gparted, it worked for me. But I'm having a different problem now with infinite initial setup. If you have a completely clean disk, I can't help in any way

I believe I just started having this issue myself... I found that if you have either vanilla OS (stable Debian) pre installed, or maybe any distro installed prior, it will clean the disc, but leave it as unallocated. But being that vanilla OS was already installed prior, it has issues with trying to finish the install


Trying to install the second time around (when the disc is unallocated) resulted in this error that is reported in this issue. I've been able to find a workaround by using gparted to at least create one large partition... Unsure if it matters, I avoided using a Linux based file system and just created a large NTFS one.

Rerunning the installer now, I was able to get things to install.

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
