### ISSUE TITLE
Vanilla Os 2.0 Orchid Guest operating system does not start in Virtual Box

### ISSUE THREAD

**Issue by rus100lan** [Vanilla-OS/iso-builder#274]
### Issue Description

in Virtual box when I start the machine an error occurs, the error says that I did not insert the iso image. although I set it in the settings

### Steps to Reproduce

1. Download Zip file
2. Get the iso image from Zip
3. Create a guest operating system in Virtual Box
4. Click on the settings of the guest operating system and in the Media section insert the iso image
5.Start the guest operating system

### On what version of Vanilla OS this happens?

2.0 
"Orchid"

**Comment by kbdharun** [comment]
Hi, Did you select the enable EFI (for special OSes) option in the VMs settings or during creation?

We don't support legacy install without UEFI. So that might probably be the issue here.

**Comment by rus100lan** [comment]
Thank you very much, everything worked
