### ISSUE TITLE
First time setup (Build #53) flathub error & ABRoot

### ISSUE THREAD

**Issue by Zukureneno** [Vanilla-OS/iso-builder#28]
1st Image : After installing on VM and restarting I was drop into Partition B (State B) and its Future Partition A (State A)  

2nd Image: After finishing first setup and rebooting I was booted back auto into State B (No swap happened) And flathub was not able to install its repos.

3rd Image: Had reboot and manually select grub State A instead of being auto to finally be able to finish installing flathub repos.

![image](https://user-images.githubusercontent.com/60487234/205154380-46a9208c-89ae-4b7b-ab8e-a2b23666f91d.png)

![image](https://user-images.githubusercontent.com/60487234/205154424-927dd79a-5188-4c5e-84fd-d4a596290caf.png)

![image](https://user-images.githubusercontent.com/60487234/205154464-a66b4444-e8c8-470b-ab8c-1a18c9878cd9.png)

**Comment by mirkobrombin** [comment]
Fixed some releases ago.
