### ISSUE TITLE
Vanilla OS + Lenovo Legion Laptops = Enhanced Performance with LenovoLegionLinux

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#283]
### Feature Description

> __I'd like to suggest integrating Lenovo Legion Linux (LLL) into Vanilla OS to enhance the experience for users with Lenovo Legion laptops. LLL provides essential drivers and tools that offer fine-grained control over hardware features like fan curves, power modes, and rapid charging.__

- Automatic hardware detection: Vanilla OS could automatically detect compatible Lenovo Legion models during installation or driver setup. This eliminates the need for manual identification and ensures users receive the relevant LLL components.
- Seamless integration: LLL features could be directly accessible within Vanilla OS settings or utilities. For example, fan control options could be integrated into the power management panel, while keyboard backlighting adjustments could be available through system settings.
- Dedicated app (optional): While integration within existing tools is preferred, considering the extensive features LLL offers, a dedicated app could be provided for advanced users seeking granular control.

### Rationale

- Enhanced user experience: LLL unlocks valuable features unavailable in the stock Linux kernel, allowing users to optimize performance, reduce noise, and extend battery life. This aligns perfectly with Vanilla OS's focus on a polished and customizable desktop experience.
- Community-driven development: LLL is an actively developed project with a dedicated community, ensuring continued improvement and maintenance. This reduces the burden on Vanilla OS developers while benefiting users directly.
- Increased appeal for gamers: Lenovo Legion laptops are popular among gamers. Integrating LLL would strengthen Vanilla OS's appeal to this tech-savvy user base, offering a feature-rich and optimized platform for their gaming needs.

> I believe integrating LLL in the manner described would benefit both Vanilla OS and its users. The automatic detection and seamless integration address technical hurdles, while the feature set and community appeal further solidify the value proposition. I encourage the Vanilla OS team to consider this suggestion and explore the possibilities of bringing LLL to their fantastic distro.

### Additional Information

Additional Resources:

- Lenovo Legion Linux GitHub Repository: https://github.com/johnfanv2/LenovoLegionLinux

Thank you for your time and consideration.

**Comment by taukakao** [comment]
Something like this can be implemented with Custom Images.
This will probably not be maintained by the vanilla team but other people can do that and distribute their image.

**Comment by mirkobrombin** [comment]
Closing as per non activity.
