### ISSUE TITLE
AppImage Support in Orchid 2.0 Alpha:

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#285]
### Feature Description

- _I've noticed that AppImage functionality, which worked seamlessly in the stable version, appears to be absent in Orchid 2.0 Alpha. I'm unsure if this is an intentional change or a bug that needs addressing._

### Rationale

- AppImages offer a unique blend of flexibility and convenience, allowing users to enjoy a vast array of applications without complex installation processes. Their self-contained nature aligns perfectly with Vanilla OS's commitment to a clean and streamlined user experience.
- Restoring AppImage support would not only enhance Orchid's versatility but also reaffirm your dedication to empowering users with choice and flexibility.

### Additional Information

I'm aware of the exciting potential of Sideload to seamlessly integrate Android APKs and DEB packages. However, I believe that integrating AppImage support within Sideload would create an even more comprehensive and user-friendly experience.

**Comment by mirkobrombin** [comment]
Hi, please have a read here: https://github.com/Vanilla-OS/desktop-image/issues/26

**Comment by mirkobrombin** [comment]
Closing as per non activity
