### ISSUE TITLE
Bluetooth driver not working on LENOVO Legion 5 15ACH6H with Vanilla OS

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#286]
### Issue Description

I'm experiencing issues with the Bluetooth driver on my LENOVO Legion 5 15ACH6H laptop while running Vanilla OS. Bluetooth is not detected at all, and no Bluetooth devices are listed in the settings.

### Steps to Reproduce

Boot up the LENOVO Legion 5 15ACH6H with Vanilla OS.
Open the system settings.
Navigate to the Bluetooth section.
Observe that no Bluetooth adapter is listed and no Bluetooth devices are detected.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by RaulKong898** [comment]
[Screencast from 2023-12-29 23-15-53.webm](https://github.com/Vanilla-OS/live-iso/assets/121046976/d3dec614-f11e-49d6-99fc-c4e3f28b09c3)

**Comment by taukakao** [comment]
This is either a problem with Debian or the Linux Kernel, please report it there.
