### ISSUE TITLE
Error encountered during update check: "package diff server returned non-OK status 400 Bad Request"

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#288]
### Issue Description

I'm experiencing an error when attempting to check for updates on Vanilla OS 2.0 Orchid Alpha. The specific error message is "package diff server returned non-OK status 400 Bad Request."

### Steps to Reproduce

1. Open a terminal window.
2. Execute the command vso sys-upgrade check.
3. Observe the error message "package diff server returned non-OK status 400 Bad Request."
4. I was expecting to get upset that I don't have updates or that I don't get the error.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.

---

This should be already fixed anyway.
