### ISSUE TITLE
Package installation with vso sideload command resulted in errors

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#289]
### Issue Description

I attempted to install a DEB package using the vso sideload command, but the installation process produced errors. Please refer to the attached screenshot for the specific error messages.

### Steps to Reproduce

1. Open a terminal window.
2. Execute the following command, replacing "package_name.deb" with the actual name of the DEB package: vso sideload package_name.deb
3. Observe any error messages that appear during the installation process.
![Screenshot from 2024-01-01 15-15-30](https://github.com/Vanilla-OS/live-iso/assets/121046976/ce03254c-a0bf-4795-a9e0-dcc6e1ca956c)

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

The installed application does not appear in the application menu either.

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.
