### ISSUE TITLE
AppImages not working (Missing FUSE)

### ISSUE THREAD

**Issue by Zukureneno** [Vanilla-OS/iso-builder#29]
AppImages are currently not working cause they require FUSE

![image](https://user-images.githubusercontent.com/60487234/205156518-5b026bc3-1dd2-4575-b3bf-e041fbfbd8ad.png)

**Comment by Teh404Gal** [comment]
Did you install the os with the app image option in the installer ticked?

**Comment by Zukureneno** [comment]
> Did you install the os with the app image option in the installer ticked?

It's pre-selected. I left everything on default. So yes the AppImage option was on same as flatpak.

**Comment by mks-h** [comment]
This issue should be closed now due to the stable release. If the issue is still present, it can always be reopened.

**Comment by kbdharun** [comment]
> This issue should be closed now due to the stable release. If the issue is still present, it can always be reopened.

I fixed it a few weeks ago, I forgot to add `Closes #29` to my PR. OP can you close this issue.
