### ISSUE TITLE
Microphone records audio too loudly, even at minimum volume setting.

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/iso-builder#292]
### Issue Description

Microphone records audio too loudly, even at minimum volume setting.

### Steps to Reproduce

1. Open any application that uses the microphone (e.g., voice recorder, video conferencing software).
2. Set the microphone volume to its minimum level.
3. Begin recording audio.
4. Observe that the recorded audio is still too loud, despite the minimum volume setting.

https://github.com/Vanilla-OS/live-iso/assets/121046976/488e9275-9fbc-4a8c-8e5a-2f510e4ae3b6

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
This is probably not a vanilla bug, but either something with your microphone driver or a debian issue.

**Comment by RaulKong898** [comment]
> This is probably not a vanilla bug, but either something with your microphone driver or a debian issue.

And how could I solve this problem? Could you tell me?

**Comment by taukakao** [comment]
> And how could I solve this problem? Could you tell me?

I sadly have no idea. I suggest asking in some debian forum.

**Comment by mirkobrombin** [comment]
Closing this issue as it pertains to the alpha version, and we are transitioning to the beta release. If the issue still exists or is relevant in the beta version, please feel free to reopen with updated information.

Thank you for your contribution and understanding.

--

My 2 cents, that looks more a hardware problem, a connection problem or a dirty port. In anyway, that's pretty hard to debug and as Tau suggested, worth asking to the Debian community.
