### ISSUE TITLE
lpkg --unlock failed

### ISSUE THREAD

**Issue by Alfredoes234** [Vanilla-OS/iso-builder#297]
### Issue Description

I tried to Install the latest alpha build of vanilla os 2 and it started to install but then an error paniced the program.

### Steps to Reproduce

Might not be reproduce-able

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

Might be because I used endeavourOS as my previous OS which is based on arch.
It gave me this error first:
![IMG_20240120_140427](https://github.com/Vanilla-OS/live-iso/assets/114923333/d2ae1c27-c4b7-41dc-82bd-0f331a9903c2)

**Comment by axtloss** [comment]
This is a known issue and will be fixed with https://github.com/Vanilla-OS/desktop-image/pull/60
