### ISSUE TITLE
feature request: include optional icon theme MoreWaita

### ISSUE THREAD

**Issue by mateowoetam** [Vanilla-OS/iso-builder#30]
I recently discovered the MoreWaita icon theme and I believe it is worthy of being included in the OS:

MoreWaita GitHub:
https://github.com/somepaulo/MoreWaita

**Comment by mirkobrombin** [comment]
Hi thanks for reporting. 

We cannot implement it as it is not our intention to alter the graphic aspect and branding of  third-party apps.
