### ISSUE TITLE
The screen can be lock before the first user creation

### ISSUE THREAD

**Issue by FullStuff** [Vanilla-OS/iso-builder#305]
### Issue Description

After the initial installation.
![VirtualBox_vanilla test_31_01_2024_17_36_43](https://github.com/Vanilla-OS/live-iso/assets/91438680/35a78798-09d6-449a-97ed-c3fd192f764f)
If you stay AFK for 5 minutes before creating the user, the lock screen will appear. Then, you need a password to unlock it.
![VirtualBox_vanilla test_31_01_2024_17_36_11](https://github.com/Vanilla-OS/live-iso/assets/91438680/dca2044a-2592-46cb-9edd-7032e18a852f)
The password is 'vanilla,' but it can confuse people.
This problem doesn't appear during the installation.

### Steps to Reproduce

- Install vanilla OS 2
- Restart
- Wait 5 min

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
Thanks for reporting. This is already tracked here:
<https://github.com/Vanilla-OS/first-setup/issues/289>
