### ISSUE TITLE
Latest beta ISO does not have a boot partition

### ISSUE THREAD

**Issue by joevaughan** [Vanilla-OS/iso-builder#306]
### Issue Description

Build #113 of Vanilla OS 2 Orchid (beta) does not have a proper boot partition and hence can't be started. 

![image](https://github.com/Vanilla-OS/live-iso/assets/92576588/4e920fdc-e6ef-401e-976e-b8dbe3b45118)

Difficult to test if it doesn't boot ;D 

### Steps to Reproduce

1. Download the ISO
2. Load the ISO in balena etcher
3. The message in the image is displayed. 
4. Hit Continue and burn the image to USB
5. Attempt to install in machine - USB disk doesn't boot. 

### On what version of Vanilla OS this happens?

Unreleased

**Comment by WebShapedBiz** [comment]
Same here.

**Comment by kabe-inc** [comment]
Presumably this is why I get the following error code when trying to run the ISO in a VM:

> Booting from DVD/CD...
Boot failed: Could not read from CDROM (code 9009) Booting from Hard Disk...
Boot failed: not a bootable disk
No bootable device.

**Comment by axtloss** [comment]
> Presumably this is why I get the following error code when trying to run the ISO in a VM:
> 
> > Booting from DVD/CD...
> > Boot failed: Could not read from CDROM (code 9009) Booting from Hard Disk...
> > Boot failed: not a bootable disk
> > No bootable device.

this is completely unrelated, you set your VM to legacy bios while vanilla os only support UEFI.

**Comment by axtloss** [comment]
regarding the error in balena etcher, you can just press continue and it'll work fine

**Comment by kabe-inc** [comment]
> > Presumably this is why I get the following error code when trying to run the ISO in a VM:
> > > Booting from DVD/CD...
> > > Boot failed: Could not read from CDROM (code 9009) Booting from Hard Disk...
> > > Boot failed: not a bootable disk
> > > No bootable device.
> 
> this is completely unrelated, you set your VM to legacy bios while vanilla os only support UEFI.

Thanks for the info. I followed the [documentation here ](https://handbook.vanillaos.org/2023/01/21/install-in-vm.html) but it didn't mention that. It doesn't work with virt-manager or gnome-boxes by default.

**Comment by taukakao** [comment]
The documentation is not for the beta version

**Comment by rbpawdev** [comment]
Running into the same issue with latest build 116 (build of 2/2/24).  Same issue as originally noted above, usb stick won't boot, won't even show in BIOS boot up options.  Burning in a Debian machine using Etcher.

**Comment by axtloss** [comment]
make sure your system support UEFI boot and its enabled.

**Comment by rbpawdev** [comment]
Yes my system supports UEFI and it is enabled.  Debian Bookworm and Vanilla Kinetic installation media boot fine but not Orchid.

**Comment by WebShapedBiz** [comment]
Same here, Acer Swift 3, UEFI enabled, secure boot disabled, USD drive detected in BIOS as a device but not bootable.

**Comment by xbrunx** [comment]
Same here, and UEFI enabled...

**Comment by taukakao** [comment]
Looking at 4.5 from <https://live-team.pages.debian.net/live-manual/html/live-manual.en.html#224> it seems that some UEFIs don't handle hybrid images well. 
I will make a hdd image for you to test. If it works, we need to think about if we should drop DVD/CD support.

**Comment by rbpawdev** [comment]
> Looking at 4.5 from https://live-team.pages.debian.net/live-manual/html/live-manual.en.html#224 it seems that some UEFIs don't handle hybrid images well. I will make a hdd image for you to test. If it works, we need to think about if we should drop DVD/CD support.

Great, let's see if that works

**Comment by taukakao** [comment]
I mean you can try it if you want but I'm not hopeful it works since it already crashes Boxes.
<https://github.com/taukakao/vanilla-live-iso/actions/runs/7777241141>

Also, I checked and virtually any other OS/tool uses an ISO and have an MBR sector in their live disk (Fedora, Ventoy and even debian) while we don't so the issue must be somewhere else.

**Comment by taukakao** [comment]
Also, the kinetic iso did also have the partition table.

**Comment by rbpawdev** [comment]
> Also, the kinetic iso did also have the partition table.

yep, I thought the same.  I was hopeful but skeptical.  I think this will be a deal breaker for quite a few of us.  Not knowledgeable enough to solution this myself.

**Comment by taukakao** [comment]
Hi, I possibly have a working iso. For anyone who wants to test:
https://github.com/taukakao/vanilla-live-iso/actions/runs/7777637131

The problem seems to be setting grub-efi in this line:
https://github.com/Vanilla-OS/live-iso/blob/0a6a69fd8df966fbe3d59e555298f476baa980f7/etc/auto/config#L50

From what I can tell this is because the hdd mode doesn't support the grub-efi flag, so the hybrid-iso becomes just a regular iso, which is not as compatible as a hybrid iso.

**Comment by rbpawdev** [comment]
> Hi, I possibly have a working iso. For anyone who wants to test: https://github.com/taukakao/vanilla-live-iso/actions/runs/7777637131
> 
> The problem seems to be setting grub-efi in this line:
> 
> https://github.com/Vanilla-OS/live-iso/blob/0a6a69fd8df966fbe3d59e555298f476baa980f7/etc/auto/config#L50
> 
> From what I can tell this is because the hdd mode doesn't support the grub-efi flag, so the hybrid-iso becomes just a regular iso, which is not as compatible as a hybrid iso.

The unzipped iso has a date of 1/30/24.  Did you package the right file in the zip?

**Comment by taukakao** [comment]
It sets the date automatically so it should have the current date.
Make sure you downloaded the right file and that you are working with the newest .zip
If you already downloaded it before the new one might be called VanillaOS2(1).zip or something

**Comment by rbpawdev** [comment]
Thanks Taukakao, the file worked to get me to a bootable usb stick and to the Vanilla Installation but then it just hangs forever once I get to the Installation point.  I will try on different hardware over the next few days.  Thanks for looking into this, your changes helped.

**Comment by WebShapedBiz** [comment]
> Hi, I possibly have a working iso. For anyone who wants to test: https://github.com/taukakao/vanilla-live-iso/actions/runs/7777637131
> 
> The problem seems to be setting grub-efi in this line:
> 
> https://github.com/Vanilla-OS/live-iso/blob/0a6a69fd8df966fbe3d59e555298f476baa980f7/etc/auto/config#L50
> 
> From what I can tell this is because the hdd mode doesn't support the grub-efi flag, so the hybrid-iso becomes just a regular iso, which is not as compatible as a hybrid iso.

Thank you @taukakao, that ISO image worked fine for me.

**Comment by taukakao** [comment]
Fixed by #311
