### ISSUE TITLE
VanillaOS-2-testing.20240130.iso fails to boot from usb

### ISSUE THREAD

**Issue by fastrizwaan** [Vanilla-OS/iso-builder#308]
### Issue Description

VanillaOS-2-testing.20240130.iso fails to boot from usb

### Steps to Reproduce

1. download VanillaOS-2-testing.20240130.iso 
2. using etcher try to create usb (ethcher will show error)
3. ignore the error, create the bootable usb
4. reboot the computer, try to boot using bootable usb.
5. boot won't work.

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

VanillaOS-2-testing.20240130.iso also fails to boot from usb. 

etcher is showing this:

![image](https://github.com/Vanilla-OS/live-iso/assets/1161682/ec7f48d5-be96-4461-b59d-730896efdc66)

```
[rizvan@dell-fedora amd64]$ cat VanillaOS-2-testing.20240130.sha256.txt; sha256sum VanillaOS-2-testing.20240130.iso 
50e0ed9362c2230492c004a7c829336e23db65f74e214b4a746193b4ba86623d  VanillaOS-2-testing.20240130.iso
50e0ed9362c2230492c004a7c829336e23db65f74e214b4a746193b4ba86623d  VanillaOS-2-testing.20240130.iso

```

**Comment by fastrizwaan** [comment]
I'm trying it on dell optiplex 9020 with legacy boot (non-UEFI)

**Comment by Pryka** [comment]
Vanilla is UEFI only distro, legacy boot(CSM) is not supported.

**Comment by taukakao** [comment]
I'm closing this since it seems to be relates to BIOS, which is not supported.

Feel free to reopen the issue if it persists on UEFI.
