### ISSUE TITLE
Problems with the GNOME Software and a few suggestions

### ISSUE THREAD

**Issue by gm64x** [Vanilla-OS/iso-builder#31]
# Problems with the GNOME Software
- Snap's - They are not appearing in the application store nor can they be installed by the terminal.
-  It is worth pointing out that I did not find any .deb applications in the store
-  -> The adoption of [eddy - a .deb installer](https://github.com/donadigo/eddy) may be a solution. This .deb installer can be found on [Pop!_OS](https://github.com/pop-os) (where it comes pre-installed) as well as an [elementary OS](https://github.com/elementary) (Can be installed by the store)
---
## Suggestions:

And I would like to suggest the possibility to add the support in the .aur and .dnf on  gnome-software using [apx](https://github.com/Vanilla-OS/apx). 

As well as the possibility of creating or downloading/installing subsystems from the application [Vanilla OS Control Center](https://github.com/Vanilla-OS/vanilla-control-center), I believe this would make it easier for users to avoid the terminal.

**Comment by Teh404Gal** [comment]
Snap problem can be fixed with adding the gnome software plugin during install if selected

Also deb in gnome store is kinda out of scope of the project since you are meant to use flatpak/snaps/appimage instead of apx since every install requires a restart kinda like fedora ostree

**Comment by Teh404Gal** [comment]
Also the fedora rpm and aur programs can be installed with the built in distrobox command

**Comment by kbdharun** [comment]
You can create a container for installing `aur` or `dnf` packages using `apx`. And if it's a GUI program, `.desktop` file will be automatically created and the application will be added to the gnome applications menu.

Cli applications can be used by `apx --aur run    {{package_name}}` or `apx --dnf run {{package_name}}`.

Also, applications are listed under the subsystem I think under the Vanilla-control-center where you can easily access and run them.

**Comment by lavilao** [comment]
> Snap problem can be fixed with adding the gnome software plugin during install if selected
> 
> Also deb in gnome store is kinda out of scope of the project since you are meant to use flatpak/snaps/appimage instead of apx since every install requires a restart kinda like fedora ostree

I dont think it requires a reboot given that vanilla os can be toggle mutable at runtime.

**Comment by gm64x** [comment]
> Also deb in gnome store is kinda out of scope of the project since you are meant to use flatpak/snaps/appimage instead of apx since every install requires a restart kinda like fedora ostree

I think that adopting the ability to install a .deb file is beneficial because it helps bring in users who use software that is not available in the store like [pureRef - Application to organize reference images](https://www.pureref.com/)  and of course there are other open source options like [beefRef](https://flathub.org/apps/details/org.beeref.BeeRef), but like windows users ... changing the workflow can be a definite point to avoid this transition to a new system

**Comment by lavilao** [comment]
> > Also deb in gnome store is kinda out of scope of the project since you are meant to use flatpak/snaps/appimage instead of apx since every install requires a restart kinda like fedora ostree
> 
> I think that adopting the ability to install a .deb file is beneficial because it helps bring in users who use software that is not available in the store like [pureRef - Application to organize reference images](https://www.pureref.com/) and of course there are other open source options like [beefRef](https://flathub.org/apps/details/org.beeref.BeeRef), but like windows users ... changing the workflow can be a definite point to avoid this transition to a new system

You can install deb files, just instead of with apt with apx. Even archlinux packages with apx --aur
