### ISSUE TITLE
[Duplicate Issue] Installation seem block on step 20 ( Setup [20/20]: lvm-luks-format )

### ISSUE THREAD

**Issue by mathys-lopinto** [Vanilla-OS/iso-builder#317]
### Issue Description

When we choose to encrypt the disk and choose a password (lower and upper letter + number + symbol) we have 20 steps to the installation. It's been more than one hour i'm lock on the last step (20), and the only thing I have on the installation log is ``Setup [20/20]: lvm-lkus-format``.
For information, i have this bug on my computer (I5 13gen U) with 500gb disk, but on my VM with only 64 GB disk, I have the same problem.

### Steps to Reproduce

- Download on [github](https://github.com/Vanilla-OS/live-iso/actions/runs/8179234255) the iso VanillaOS-2-testing.20240306.iso
- Make it bootable using balena etcher
- boot on the usb stick on the computer
- Select the Install Vanilla OS 2.0
- Select install 
- Select en_gb language
- Select French (AZERTY) keyboard
- Connect to the wifi
- Select Europe/ Paris timezone
- choose a password (lower and upper letter + number + symbol) for the disk encryption
- select disk and select use all disk
- launch the instalation

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

I have the same problem on VM, and on the discord other person got the same problem.

**Comment by mathys-lopinto** [comment]
![IMG_20240316_135907759.jpg](https://github.com/Vanilla-OS/live-iso/assets/55036267/82379576-ff35-4574-9ab0-8c1b0ce21aa4)

Here it's my POV (the install start at 10h30), and i have install htop at 12h50 for see if installer really do something

**Comment by mathys-lopinto** [comment]
![IMG_20240316_140749224.jpg](https://github.com/Vanilla-OS/live-iso/assets/55036267/1ccd7afe-52b1-4d83-b6a0-c29662e32ee2)



And as we can see on my image there are NO tasks containing lvm or luks, like if the installer cannot detect the task successfully finished.

**Comment by mathys-lopinto** [comment]
And if i'm doing the same step but i choose manual partitioning i have the same bug on step 14 ``Setup [14/14] : luks-format``

**Comment by callb4ck** [comment]
Having the exact same issue. I'm trying with older images

**Comment by callb4ck** [comment]
So.

As of now there are four beta builds.

118 (latest) - Didn't work.

117 - Didn't work.

116 - Worked after installer crash!

113 - Didn't work.

So yeah, try build 116

**Comment by ghost** [comment]
https://github.com/Vanilla-OS/Albius/issues/58

**Comment by taukakao** [comment]
As @zehkira mentioned, this is an Albius bug and already tracked there. 
I'm closing this issue.
