### ISSUE TITLE
Installer crashes

### ISSUE THREAD

**Issue by code-leech** [Vanilla-OS/iso-builder#321]
### Issue Description

The installer crashes randomly when it is partitioning the disk.

### Steps to Reproduce

Start installer

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
Are you using Wifi?

**Comment by code-leech** [comment]
Yes

**Comment by code-leech** [comment]
Kinda annoying as it wiped my whole disk

**Comment by Bohne13** [comment]
Had the same problem. @taukakao helped me kinda 'fix' it.

1. You should format the Drive you want to install VOS as ext4.
2. When yo started the live-ISO login to your WiFi via the system settings and than start with the installer.

**Comment by taukakao** [comment]
Still not sure why it happens but it's already tracked [here](https://github.com/Vanilla-OS/vanilla-installer/issues/301) so I'm closing this. We need more info, I can sadly not replicate it.
