### ISSUE TITLE
There is no way to run VanillaOS 2 orchid without a UEFI module

### ISSUE THREAD

**Issue by NewTechDesign** [Vanilla-OS/iso-builder#334]
### Issue Description

Hello, is it possible to bypass this limitation?

### Steps to Reproduce

I am interested in your project with an interesting design and support for arch files, is it possible to solve my problem?

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
As discussed on Discord, this is not supported.
