### ISSUE TITLE
Provide download mirrors or CDN for installer ISOs

### ISSUE THREAD

**Issue by skylarmb** [Vanilla-OS/iso-builder#339]
### Feature Description

The current system of downloading via the github actions artifacts is incredibly slow. Github seems to limit these artifact downloads to about 600kbps no matter what your actual internet speed is. This means it takes 30-40 minutes to download the installer ISO even on a 2.5Gbps fiber connection for example. A simple CDN cache or mirror would be a huge user experience improvement. 

![Screenshot from 2024-07-11 11-01-04](https://github.com/Vanilla-OS/live-iso/assets/7543705/a46f6730-fd94-49ef-8df5-9288778123b9)

### Rationale

I love installing and trying new operating systems, and this greatly reduces the chances of me trying out VanillaOS

**Comment by GabsEdits** [comment]
As far as I know, Vanilla OS Stable will provide a CDN from https://cdn.vanillaos.org/, just like Kinetic did.

**Comment by taukakao** [comment]
Yeah, this is because Orchid is in beta. 
The stable version will be distributed over our CDN.
