### ISSUE TITLE
Mouse scaling problem

### ISSUE THREAD

**Issue by czM1K3** [Vanilla-OS/iso-builder#34]
Hello,
I have installed build from December 21 2022 and I have problem with mouse scaling in apps installed with apx.
For example, I have installed Xournal++. When scaling is set to 100%, there is no problem. When I set scaling to 200%, when I hover over application, mouse cursor is really small. When I enable fractional scaling and set scaling to 150%, the cursor is really small and also cropped. I have recorded it on video: https://user-images.githubusercontent.com/45005362/208997730-75985812-1ef2-457b-9435-ca75dd0cf865.mp4
Also, I'm in Wayland session.

**Comment by mirkobrombin** [comment]
This is a problem of some applications with Wayland and there is nothing we can do in Vanilla OS to fix. I was able to replicate on Fedora using Telegram.
