### ISSUE TITLE
Panic: failed to run setup operation format: failed to make file system for /dev/sda2: 1: mkfs.: not found

### ISSUE THREAD

**Issue by gilbertoferreira** [Vanilla-OS/iso-builder#346]
### Issue Description

Tried to install in a Virtualbox.
Got this 
Panic: failed to run setup operation format: failed to make file system for /dev/sda2: 1: mkfs.: not found

### Steps to Reproduce

- Using Virtualbox
- Create partitions:
- > /dev/sda1 - 1G - /boot
- > /dev/sda2 - 1G - EFI (extfat)
- > /dev/sda3 - 8G - swap
- > /dev/sda5 -> 120G - root
- > /dev/sda6 -> 70G - var

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

![image](https://github.com/user-attachments/assets/d0facf5e-5703-4bb7-b67c-5459c5452f6e)

**Comment by taukakao** [comment]
Thanks for reporting. I'm closing this tho since the bug is tracked here: https://github.com/Vanilla-OS/Albius/issues/74
