### ISSUE TITLE
vanilla.zip ? What is it ?

### ISSUE THREAD

**Issue by Xdavius** [Vanilla-OS/iso-builder#349]
### Issue Description

Click on download on the website, got a vanilla.zip

don't understant what is it

### Steps to Reproduce

-go to website
-click download

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

Better the download button to point to the .ISO

**Comment by taukakao** [comment]
The zip file contains the ISO, you need to extract it

**Comment by kbdharun** [comment]
Hi, If you need the direct ISO I would suggest checking out the releases here -> https://github.com/Vanilla-OS/live-iso/releases. The file you get from CDN is zipped for better download time and reliability (for people with lower speeds), additionally, it includes the checksum files inside it for verification purposes.

**Comment by Xdavius** [comment]
> The zip file contains the ISO, you need to extract it

Hum.. that was a download bug. Zip was 9.1Mb. Sorry about that.

> . The file you get from CDN is zipped for better download time and reliability (for people with lower speeds), additionally, it includes the checksum files inside it for verification purposes.

The zip format doesn't decrease file size. Or not sinificatively. But it add a step for the end user. Not sure it's a good choice IMO. 

sha256sum can be added above the button...

That's just an opinion =)

regards.

**Comment by taukakao** [comment]
You're probably right. Tracked here now:
https://github.com/Vanilla-OS/website/issues/230
