### ISSUE TITLE
Flatpak not installing on my system.

### ISSUE THREAD

**Issue by GavBog** [Vanilla-OS/iso-builder#36]
First Setup isn't installing Flatpak!

**Comment by GavBog** [comment]
I believe this is a duplicate of #28

**Comment by GavBog** [comment]
Appimages aren't broken. Just didn't give it the executable permissions :)

**Comment by GavBog** [comment]
Flatpak still broken though!

**Comment by kbdharun** [comment]
> Flatpak still broken though!

Check your internet connection. I even did a fresh install right now. And all flatpaks installed seamlessly.

> Appimages aren't broken. Just didn't give it the executable permissions :)

This ☝🏽 , I fixed the packages and tested them too. So it must definitely work.

**Comment by GavBog** [comment]
Was fixed with

https://github.com/Vanilla-OS/ABRoot/commit/1e86593439b12cd733875a19e66c3286ee2d3410
