### ISSUE TITLE
Unable to Install VanillaOS Orchid

### ISSUE THREAD

**Issue by MagTheDev** [Vanilla-OS/iso-builder#370]
### Issue Description

The installer failed with grub-install claiming /mnt/a/boot/efi is not an EFI partition
Relevant logs attached
```Image pulled with digest 5187f0ecffb3db88al6ded468fe08eeacc59513fe835fbc0c3687al35a803d6b
Image mounted at /mnt/a/var/storage/graph/overlay/b65939de87a083ae2c06a8148aaf5255f9730a1c309f627d8b839456caeee25/merged
Copying image to /mnt/a update-initramfs: Generating /boot/initrd. img-6.9.8-amd64
Post-installation [1/22]: shell Post-installation [2/22]: shell Post-installation [3/22]: shell
Post-installation [4/22]: grub-install
panic: failed to run post-install operation grub-install: grub-install: failed t o run grub-install: Installing for x86_64-efi platform.
grub-install: error: /mnt/a/boot/efi doesn't look like an EFI partition.
goroutine 1 [running] :
main.main ()
github.com/vanilla-os/albius/albius.go:37 +0xeb```

### Steps to Reproduce

- Flash usb with image: `VanillaOS-2-stable.20240824.iso`
- Create 4 required partitions with GParted
- Run the installer
- Have the installer fail to install the OS

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

I have windows already installed on the same drive, maybe there are some issues with the windows' efi partition?

**Comment by Sn1cket** [comment]
I had a similar installation issues with this ISO: `VanillaOS-2-stable.20240824.iso`

This might be fixed in the latest ISO.
Just tried with `VanillaOS-2-stable.20241123.iso` and it worked like a charm on my side.

**Comment by taukakao** [comment]
Yup, this should be fixed.
The issue was that it formatted the partition with the wrong filesystem.

**Comment by vladislav-svetailo** [comment]
1. Flash latest Vanilla  OS on usb stick 
2. Boot from usb, select Recovery - Gparted
3. Erase all partitions from previous os
4. Install Vanilla OS amd use entire disk for automatic partitioning 

Installation process completed without errors 

Grub not found on the boot

Acer AL15-33P-39XM
