### ISSUE TITLE
Unable to install Vanilla OS 2: ISO fails to boot from USB drive

### ISSUE THREAD

**Issue by BrodyB** [Vanilla-OS/iso-builder#371]
### Issue Description

I put the latest Vanilla OS 2 stable ISO to a USB stick. When I reboot and select that volume to boot into, I'm presented with the GRUB loader, as expected. Once I select any version of the Vanilla OS 2 installer to run, I'm greeted with the following error:

`[       1.159202] hub 10-0:1.0: config failed, hub doesn't have any ports! (err -19)`

I've seen similar errors in other distros, but they quickly move past them. This error happens for all three options for launching the installer. I've also tried other USB drives.

### Steps to Reproduce

- Flashed latest image to USB drive
- Boot into drive
- Received error

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

System Specs
- AMD Ryzen 7 78003DX
- DDR5 RAM (32GB)
- GeForce RTX 4070 Ti (12GB)
- NVMe M.2 drive (2TB)
- NVMe M.2 drive (2TB)
- NVME M.2 drive (1TB)  <- Destination, currently formatted as FAT

**Comment by abdullahalydev** [comment]
did you solve the problem? @BrodyB

**Comment by BrodyB** [comment]
> did you solve the problem? @BrodyB

I just downloaded the latest version from the site, wrote it to a USB drive, and it appears to be working now! I guess they got through the issues that prevented my system from launching the installer!
