### ISSUE TITLE
Xterm, UXTerm and GNOME Terminal installed by default together with GNOME Console

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/iso-builder#40]
Probably leftovers? I don't get why anyone needs 4 terminal emulators.

![Screenshot from 2022-12-29 23-29-16](https://user-images.githubusercontent.com/51861383/210022251-f14ac698-cbbf-4540-a545-0ac67edd90b1.png)

**Comment by kbdharun** [comment]
> Probably leftovers? I don't get why anyone needs 4 terminal emulators.


I will remove it, give me a couple of minutes.

**Comment by sbe-arg** [comment]
Still happening between gnome-teminal and gnome-console
See #70

**Comment by kbdharun** [comment]
> Still happening between gnome-teminal and gnome-console
> See #70

I had informed regarding this is Discord. Unlike Xterm, which was easily removed. Gnome terminal seems to be installed with the gnome shell unfortunately. Removing it requires some work.

Gnome console is included by us unlike the terminal.

**Comment by mirkobrombin** [comment]
Fixed some releases ago.
