### ISSUE TITLE
Nvidia Driver installation not working and driver options not showing on Vanilla OS Control Center

### ISSUE THREAD

**Issue by pedro-hro** [Vanilla-OS/iso-builder#41]
After the installation (that worked well), when the configuration is done with "First Setup" and the system is rebooted, the chosen apps from First Setup and the Nvidia Drivers are not installed. I did a lot of installation tries and tried a few different things to solve like turning the internet on and off during installation and First Setup, entered in Xorg session before the First Setup, and finally tried to install nvidia-driver-525(and 510, 470, etc) package manually inside de ABRoot Shell. This last try gave-me the following problem:
`Errors were encoutered while processing: linux-image-5.19.0-26-generic  E:Sub-process /usr/bin/dpkg returned an error code (1)`

The only way the setup worked was by skipping the Nvidia driver installation in First Setup. Then the chosen apps were installed normally but in the Vanilla OS Control Center it says that there are no drivers available.

In the Discord someone said about possibility of my GPU not been listed in the Ubuntu drivers list but I already checked that, I'll link the image of the output.

![image](https://user-images.githubusercontent.com/49164063/210029612-b9f1f853-da47-48ad-8819-b74b9362de41.png)
![image](https://user-images.githubusercontent.com/49164063/210029717-3ee3a1d8-cc77-4875-9d64-de646059740e.png)

**Comment by futured-it** [comment]
I have the same problem

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/Vanilla-OS/vanilla-control-center/commit/0cda2d548ef4fdba0fdc4abfc8ab4beee1ec2816

An update and a new ISO will be available soon.
