### ISSUE TITLE
Question about ABroot

### ISSUE THREAD

**Issue by lavilao** [Vanilla-OS/iso-builder#43]
Hi I have been reading about vanilla os and how now manages immutability through ABroot. Overall is a really cool tech like the ones of chromeos and deepin are using to have a 2 root partition system but there is something I still can't understand: the space requirements of 40gb (20 for each root) to use it. If vanilla os was using ext4 I would get it, like in deepin, You need to copy the contents from root to root thus the need of space but vanilla os by default does not use ext4 it uses btrfs (according to this https://vanillaos.org/2022/11/01/vanilla-installer.html). Si why use a sepárate partition and 20 extra GB when You can use snapshots to achieve the same with only 1 partition and only the diff space, using btrfs reflinks is also way more faster than copying 20gb of data from 1 partition to another. Has the default filesystem changed thus making a 2nd partition a need? Thanks in advice.
PD: this is not because of hate, all the contrary, is because I want to install vanilla os but I only have 25gb available for root 😕.

**Comment by mks-h** [comment]
Please see [this message](https://github.com/Vanilla-OS/vanilla-installer/issues/83#issuecomment-1367892360). In short, improvements are planned.

**Comment by lavilao** [comment]
Thanks for the answers
