### ISSUE TITLE
evolution-data-server not installed

### ISSUE THREAD

**Issue by tobehn** [Vanilla-OS/iso-builder#44]
i think GNOME Online Accounts, Calendar and Contacts heavily rely on **evolution-data-server**. 

It did not come with my fresh install. At least i get this message when trying to start Contacts from Commandline:

`flatpak run org.gnome.Contacts`

`(gnome-contacts:2): gnome-contacts-WARNING **: 18:14:47.497: contacts-esd-setup.vala:34: Couldn't load EDS SourceRegistry: Fehler beim Aufruf von StartServiceByName für org.gnome.evolution.dataserver.Sources5: Unit evolution-source-registry.service not found.`

When looking for the Unit file i couldn't find anything in `/etc/systemd/`

Would i need to install it via _abroot exec_?

**Comment by tobehn** [comment]
Yes, after installing it via _abroot_ it integrates with the system. Contacts and Calendar start and synchronize well with the Online Accounts. In my case Nextcloud. 

I think this should be on board by default.

**Comment by kbdharun** [comment]
Oh, can you share the package name here as I couldn't find it as a dependency in https://packages.ubuntu.com/kinetic/gnome-online-accounts.

Edit: NVM, Just saw the issue description.

Edit 2: I will add it tomorrow after some testing seems like it is required for the applet.
