### ISSUE TITLE
Nvidia Drivers not installing

### ISSUE THREAD

**Issue by pedro-hro** [Vanilla-OS/iso-builder#47]
After the Vanilla Control Center update I tried to install the Nvidia Drivers that now are listed in the Drivers page but it didn't work. After clicking "Apply Changes" the "Confirm Reboot" screen just pop up instantly and when rebooted the drivers are not installed. Tried to do a new installation with the ISO released today (30/12) too and got the same problem.

**Comment by pedro-hro** [comment]
[Screencast from 2022-12-30 19-46-56.webm](https://user-images.githubusercontent.com/49164063/210107004-564f7cfa-b41b-4f08-bbb9-904efafd12d7.webm)

**Comment by pedro-hro** [comment]
Also, when trying to install with the First Setup, it gave the same problems described in the issue #41 (closed): did not install and the flatpaks chosen in first setup don't install neither.

**Comment by Ophiolith** [comment]
Can confirm same issue here. Also forcing a manual install of Nvidia 525 drivers via abroot exec causes the OS to not boot at all. No failure dialogues are generated and installing via terminal returns no errrors.

**Comment by maya-doshi** [comment]
Had the same issue here.

**Comment by tommerty** [comment]
So what I'm seeing in this is when I'm trying to download the drivers vis the driver section in the Vanilla app, and it prompts you to restart I guess before it's finished downloading. I pressed cancel on the restart prompt, left it for a minute or two, then clicked it again to prompt the restart, still no Nvidia drivers installed

**Comment by mirkobrombin** [comment]
A fix is coming in a few hours. Just tested on bare metal and it works.

![image](https://user-images.githubusercontent.com/9479903/210132222-049ea129-8833-4779-9f4f-0cd255a4f1fa.png)
