### ISSUE TITLE
Fingerprint reader not detected

### ISSUE THREAD

**Issue by Dirussy** [Vanilla-OS/iso-builder#49]
My laptop is a framework and it is using the Goodix fingerprint sensor but it is not detected by gnome.
I tried to install the package by using this (told by Dharun Kirhna) : 

sudo abroot exec apt install fprintd

But instead, it made me stuck on the login screen.

For info, it is a fresh install of vanilla os.

**Comment by Dirussy** [comment]
On the Vanilla OS 22.10-r3 the issue still persist

**Comment by kbdharun** [comment]
> On the Vanilla OS 22.10-r3 the issue still persist 

Added the packages in base repo recently, you will receive it in the next update.

**Comment by Dirussy** [comment]
In the 22.10-r5 fingerprint reader is still not working

And if I install the fprintd package I still get stuck in login screen

**Comment by kbdharun** [comment]
> In the 22.10-r5 fingerprint reader is still not working
> 
> And if I install the fprintd package I still get stuck in login screen

Yeah, Base wasn't updated in r5. But the drivers were added to it. You should see it soon.

Ref: https://github.com/Vanilla-OS/vanilla-base-meta/commit/c813e3f2b1acba30cb970ac850c0e80fb3d541e0

Current base version in launchpad: 1.2.0
Base version in rep:1.2.1

**Comment by ghost** [comment]
> > In the 22.10-r5 fingerprint reader is still not working
> > And if I install the fprintd package I still get stuck in login screen
> 
> Yeah, Base wasn't updated in r5. But the drivers were added to it. You should see it soon.
> 
> Ref: [Vanilla-OS/vanilla-base-meta@c813e3f](https://github.com/Vanilla-OS/vanilla-base-meta/commit/c813e3f2b1acba30cb970ac850c0e80fb3d541e0)
> 
> Current base version in launchpad: 1.2.0 Base version in rep:1.2.1

Not sure if Linux supports, but is it possible to get IR support for face unlock?

**Comment by bketelsen** [comment]
> Not sure if Linux supports, but is it possible to get IR support for face unlock?

You're looking for [howdy](https://github.com/boltgolt/howdy)

**Comment by mirkobrombin** [comment]
We should offer it in the vanilla os PPA

**Comment by Dirussy** [comment]
Update there is still no fingerprint detecded on 22.10-r6

**Comment by kbdharun** [comment]
> > In the 22.10-r6 fingerprint reader is still not working
> > 
> > And if I install the fprintd package I still get stuck in login screen
> 
> Yeah, Base wasn't updated in r6. But the drivers were added to it. You should see it soon.
> 
> Ref: https://github.com/Vanilla-OS/vanilla-base-meta/commit/c813e3f2b1acba30cb970ac850c0e80fb3d541e0
> 
> Current base version in launchpad: 1.2.0
> Base version is higher.

Ping @mirkobrombin , the package must be updated in launchpad.

**Comment by ghost** [comment]
> Update there is still no fingerprint detecded on 22.10-r6

likewise

**Comment by Muqtxdir** [comment]
hi @kbdharun @Dirussy 

are you guys sure that adding these packages will resolve it?

**Comment by kbdharun** [comment]
> are you guys sure that adding these packages will resolve it?

I am pretty sure it will work, Another user  tested these packages and it seem to fix this issue. 

I would suggest having this open for some time till the base update to ensure that it is fixed.

**Comment by kbdharun** [comment]
Ok, now the base update is out. Anybody can test it out again and let us know if the fingerprint issue is gone.

**Comment by Dirussy** [comment]
Update the fingerprint is detected and working thank

**Comment by kbdharun** [comment]
> Update the fingerprint is detected and working thank

Thanks for the information. Glad it works. Can you close this issue?

**Comment by ghost** [comment]
> Update the fingerprint is detected and working thank

Likewise, my fingerprint is working too, thanks
