### ISSUE TITLE
GVfs not showing in Nautilus Sidebar

### ISSUE THREAD

**Issue by tobehn** [Vanilla-OS/iso-builder#51]
I have another issue wit Gnome Online Accounts.
https://wiki.gnome.org/Projects/GnomeOnlineAccounts

By setting up a Nextcloud connection i can choose syncing Calendar, Contacts and Files. Calendar and Contacts are working fine after this #44 fix 👌.

However, the WebDAV Connection is not showing up in Nautilus Sidebar as it normally does by switching on File sync in the configuration of the Online Account.

I dug into it a little bit, i am not familiar with how this is done in GNOME though. From how i understand a mount should have been generated automatically which shows up in the sidebar then.

There is something to read about GVFS which is a virtual filesystem implementation for GIO --> GVolumes.

About the Integration with GOA:
https://wiki.gnome.org/Projects/GnomeOnlineAccounts/Debugging

About the GNOME Virtual File System:
https://wiki.gnome.org/Projects/gvfs/

- `gvfs-mount -l` command is not available.
- **gvfs-goa-volume-monitor** binary is not shipped with the installation (i assume)
- > The GVfs integration is hinged on the [org.gnome.OnlineAccounts.Files](https://developer.gnome.org/goa/stable/gdbus-org.gnome.OnlineAccounts.Files.html) interface. GVfs' GOA volume monitor exposes all account objects implementing this interface as GVolumes that appear in the above output. You can mount and unmount volumes from the GTK+ UI or with gvfs-mount:

Perhaps it just helps to have the whole **gvfs** aboard (https://gitlab.gnome.org/GNOME/gvfs)

**Comment by kbdharun** [comment]
So, adding `gvfs-goa-volume-monitor` is enough right? I am adding another package currently will add it too.

**Comment by tobehn** [comment]
i am not sure. i havent testet it.
i was wondering if this could be done via vanilla_base_meta again.

tarballs of **gvfs** can be found here:
https://download.gnome.org/sources/gvfs/

**gvfs-goa-volume-monitor** is part of it (afaik)
`gvfs-mount` command could then be available.

**Comment by kbdharun** [comment]
> i am not sure. i havent testet it. i was wondering if this could be done via vanilla_base_meta again.
> 
> tarballs of **gvfs** can be found here: https://download.gnome.org/sources/gvfs/
> 
> **gvfs-goa-volume-monitor** is part of it (afaik) `gvfs-mount` command could then be available.

I will check Ubuntu packages (https://packages.ubuntu.com/) and will get back to you.

**Comment by kbdharun** [comment]
https://packages.ubuntu.com/kinetic/gnome-online-accounts, It seems to be listed here already so it must be installed. Can you try to installing `gvfs` (https://packages.ubuntu.com/kinetic/gvfs) alone though abroot (`sudo abroot exec apt install gvfs`) and let me know. If it works.

**Comment by tobehn** [comment]
I could install it via _abroot_. I do not have the `gvfs-mount` command afterwards and also when starting Nautilus i do not see any mounts. 

I assume a deamon, or any kind of service needs to be startet. Stlll figuring out.

EDIT:
Service was running:
```
systemctl --user status gvfs-daemon
● gvfs-daemon.service - Virtual filesystem service
     Loaded: loaded (/usr/lib/systemd/user/gvfs-daemon.service; static)
     Active: active (running) since Sat 2022-12-31 13:51:38 CET; 13min ago
   Main PID: 1938 (gvfsd)
      Tasks: 12 (limit: 18743)
     Memory: 3.8M
        CPU: 93ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/gvfs-daemon.service
             ├─1938 /usr/libexec/gvfsd
             ├─1955 /usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f
             └─2310 /usr/libexec/gvfsd-trash --spawner :1.8 /org/gtk/gvfs/exec_spaw/0

Dez 31 13:51:38 vanilla systemd[1891]: Starting Virtual filesystem service...
```

**Comment by tobehn** [comment]
you also need to add the package _gvfs-backends_

i have it working now.

**Comment by kbdharun** [comment]
> you also need to add the package _gvfs-backends_
> 
> i have it working now.

Thanks so I need to add these 2 packages for nextcloud to work right? or does it apply to all gnome-online-account profiles?

I will add it, I need more info for changelog description.

**Comment by tobehn** [comment]
I assume it’s for all GNOME Online Account Integrations. 
_gvfs-backends_ has several integrations aboard.

See https://packages.ubuntu.com/kinetic/amd64/gvfs-backends/filelist

It is at least needed to get the _gvfs-goa-volume-monitor_ binary and service into the system.

**Comment by kbdharun** [comment]
> I assume it’s for all GNOME Online Account Integrations. _gvfs-backends_ has several integrations aboard.
> 
> See https://packages.ubuntu.com/kinetic/amd64/gvfs-backends/filelist
> 
> It is at least needed to get the _gvfs-goa-volume-monitor_ binary and service into the system.

`gvfs-backend` has `gvfs` as dependency so adding it alone is enough I think <https://packages.ubuntu.com/kinetic/gvfs-backends>. Thanks for helping me out, I will create a PR now.

**Comment by tobehn** [comment]
Great! You are welcome.
🚀
