### ISSUE TITLE
First setup still present after successful install

### ISSUE THREAD

**Issue by penlinaco** [Vanilla-OS/iso-builder#52]
After successful installation, the first setup program is still visible in the gnome applications menu.

**Comment by kbdharun** [comment]
> After successful installation, the first setup program is still visible in the gnome applications menu.

I think it is intended because you can always rerun it in future if you need to disable flatpaks or install drivers.

**Comment by penlinaco** [comment]
For adding more flatpaks etc. It worked fine, but I couldn't get it to remove anything. It seems like deselecting options do nothing - but that would be an entirely different problem.

**Comment by kbdharun** [comment]
> For adding more flatpaks etc. It worked fine, but I couldn't get it to remove anything. It seems like deselecting options do nothing - but that would be an entirely different problem.

I think we could add code for the deselecting to work in a rerun. (We will work on it in future).

**Comment by penlinaco** [comment]
Thank you very much for your quick responses.
