### ISSUE TITLE
support for Raspberry pi 4B ?

### ISSUE THREAD

**Issue by AmirulAndalib** [Vanilla-OS/iso-builder#53]
### Feature Description

hi thank you for your cool project. I would like to ask if the Vanilla OS latest version is available for Raspberry pi 4B ? the architecture of the raspberry pi 4B is aarch64 aka Arm64

### Rationale

enhancements and adding support for Raspberry pi 4B

**Comment by AmirulAndalib** [comment]
its been 2 weeks didnt get any reply :/

**Comment by mirkobrombin** [comment]
The whole team is busy, the exit of the stable has caused a lot of people to approach the project with questions, doubts and a few bugs here and there. Almost all communications and reports take place on discord. I'm sorry your issue got lost.

We made a video faq weeks ago where we announced that we plan to deploy an ISO for ARM devices in the future.

**Comment by AmirulAndalib** [comment]
> The whole team is busy, the exit of the stable has caused a lot of people to approach the project with questions, doubts and a few bugs here and there. Almost all communications and reports take place on discord. I'm sorry your issue got lost.
> 
> We made a video faq weeks ago where we announced that we plan to deploy an ISO for ARM devices in the future.

thanks for further reply i hope vanilla os for arm devices gets support soon .
