### ISSUE TITLE
Cannot set different (non-fractional) scaling for multiple monitors

### ISSUE THREAD

**Issue by lunacd** [Vanilla-OS/iso-builder#55]
### Issue Description

With stock Ubuntu and Fedora, GNOME is able to automatically detect and apply appropriate scales (100%/200%) to different monitors. This does not happen with VanillaOS.

When trying to manually set the scale, setting the scale of one affect both displays, i.e. they can either both 100% or 200% for some reason.

### Steps to Reproduce

- Install VanillaOS and plug in two displays of different appropriate scales.
- Observe the appropriate scale is not automatically applied.
- Manually setting scale of one affect both.

### On what version of Vanilla OS this happens?

22.10

**Comment by Muqtxdir** [comment]
hi @andyliuhaowen 

you can change integer-scaling/frac-scaling if the displays are in join mode not in mirror mode.
