### ISSUE TITLE
[apx] apx commands throw error messages with Nvidia driver

### ISSUE THREAD

**Issue by lunacd** [Vanilla-OS/iso-builder#56]
### Issue Description

When executing `apx shell`, the output is
```
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve
```

### Steps to Reproduce

- Install VanillaOS and NVidia propriatary graphics.
- Run `apx shell`.

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
Apx shell does not exist. 
Regarding the error (which is not blocking): https://github.com/Vanilla-OS/apx/issues/16

closing as duplicate.
