### ISSUE TITLE
Overcoming ABRoot immutability by opening a new transaction shell inside the previous one.

### ISSUE THREAD

**Issue by cooligula** [Vanilla-OS/iso-builder#58]
### Issue Description

During an ABRoot transaction shell, if you face errors, when exiting the transaction the changes won't be applied but if after receiving the error you try to open a new transaction shell without exiting the previous one and then exit the transaction, the changes done before the error will still be applied and the transaction will be marked as successful.

### Steps to Reproduce

`>sudo abroot shell`
`>...`
`ERROR`
`>sudo abroot shell`
`Transaction is locked`
`>exit`
`Transaction successful`

### On what version of Vanilla OS this happens?

22.10

**Comment by cooligula** [comment]
Despite this being a bug, for me it has been the only way to update the kernel despite getting an `Error: exit code (1)` with the unsigned linux-image, so I would ask this be left unsolved until there's any way to overcome this problem "in a good way".

**Comment by mks-h** [comment]
You are always able to mark a transaction as successful by exiting from the shell with `exit 0`. And if you want to mark a transaction as failed, use can use `exit 1` or any greater number.

**Comment by mirkobrombin** [comment]
This was fixed some releases ago.
