### ISSUE TITLE
Provide some deafult user profile avatars

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/iso-builder#62]
### Feature Description

Provide some default user profile avatars. On Fedora I had some, thought they were provided by GNOME.

![image](https://user-images.githubusercontent.com/51861383/210242031-6639484d-0816-49f2-8959-1d831f578c4b.png)

### Rationale

Rationale is the same as with the provided wallpapers.

**Comment by kbdharun** [comment]
Yes they are indeed provided by Gnome.

Can you install `gnome-control-center-faces` and let me know if it works?

**Comment by mks-h** [comment]
Yes, it works, thanks.

![image](https://user-images.githubusercontent.com/51861383/210244074-fbfe0620-1fc3-4778-bfcd-af624cad8b9c.png)

**Comment by kbdharun** [comment]
Great :)
