### ISSUE TITLE
Minimise and maximise button

### ISSUE THREAD

**Issue by cempack** [Vanilla-OS/iso-builder#64]
### Feature Description

Adding minimise and maximise button by default

### Rationale

It's very annoying to install gnome tweaks and do it manually so maybe you could add it by default ?

**Comment by kbdharun** [comment]
It is already available under settings in Windows -> Extended. We have integrated some functions from gnome tweaks directly in settings (gnome-control-center). [See mouse/trackpad settings, date & time, etc]

**Comment by RealFFF000** [comment]
This isn't vanillaos' issue; this is gnome's default configuration. I believe it can be changed in gnome tweaks.

**Comment by Muqtxdir** [comment]
as mentioned by @kbdharun these options are already provided in settings > windows
