### ISSUE TITLE
Black screen after installation

### ISSUE THREAD

**Issue by gokuo64** [Vanilla-OS/iso-builder#65]
### Issue Description

I have an old laptop from 2010 with an Intel Celeron p4500. I installed Vanilla os from a USB stick.  The live session and install worked fine.  But after booting my laptop for the first time, I only get a black screen.  

### Steps to Reproduce

Download iso
Make bootable USB stick with Rufus
Boot from USB on laptop
Install vanilla os
Reboot
Black screen

### On what version of Vanilla OS this happens?

22.10

**Comment by gokuo64** [comment]
I had a similar experience with clear Linux.  I think it has to do with my laptop's bios not having full UEFI support. There's not even an option in the bios for legacy vs UEFI

**Comment by HenryLongHead** [comment]
For me it's not a black screen but no bootable drive beeing detected. I'm using an Acer Predator Helios 300 with a classic BIOS, GTX 1050 TI and core I7.

**Comment by mirkobrombin** [comment]
Unfortunately we cannot replicate this and there are not enough details to predict a fix. On the other hand, I wouldn't know what details to ask, if the installation goes through it means that there are no errors.

Feel free to try one of the latest ISOs and provide more details if they come to mind.
