### ISSUE TITLE
Vulkan rendering doesn't work on anything that isn't a Flatpak.

### ISSUE THREAD

**Issue by Mars7x** [Vanilla-OS/iso-builder#69]
### Issue Description

Vulkan rendering works on Flatpaks, but not on anything else that depends on system libraries. I tested this on a Radeon RX 5600 XT and an Intel HD Graphics 505.

### Steps to Reproduce

-Install any app that doesn't depend on flatpak dependencies.
-Try using Vulkan as a graphics bandend. In my case I tested Vulkan rendering in Cemu, Yuzu, and Ryujinx.

### On what version of Vanilla OS does this happen?

22.10

### Additional Information

OpenGL works.

**Comment by Mars7x** [comment]
Necessary dependencies were added in MR [#21](https://github.com/Vanilla-OS/vanilla-base-meta/pull/21).

**Comment by kbdharun** [comment]
> Necessary dependencies were added in MR [#21](https://github.com/Vanilla-OS/vanilla-base-meta/pull/21).

Thanks. Seems like I forgot to tag this issue.
