### ISSUE TITLE
Remove either gnome-terminal or gnome console from default setup but no need for both

### ISSUE THREAD

**Issue by sbe-arg** [Vanilla-OS/iso-builder#70]
There is no need to have both terminals lets pick up one and remove the otherone from the default setup.

While easy to remove what we don' want by running

```
sudo abroot exect apt remive --purge packagename
```

Drop a comment with preference I personally like gnome-console over gnome-terminal due its mobile friendliness but not fuzzy about it.

**Comment by kbdharun** [comment]
Thanks for the report, please close this duplicate issue. We are already tracking the other one.

For now don't remove any pre-installed application as there is a bug with base auto removing applications.

**Comment by sbe-arg** [comment]
@kbdharun I did remove gnome-terminal without any problems so far have installed a few additional like gnome-logs
