### ISSUE TITLE
Unable to install system

### ISSUE THREAD

**Issue by HenryLongHead** [Vanilla-OS/iso-builder#75]
### Issue Description

Live boot created with rufus works just fine, the installer states that everything was installed succesfully, but after a reboot, no bootable drive is detected. I've used this laptop for several different linux distros previously.

### Steps to Reproduce

- Create a live boot USB with rufus
- Install it "Succesfully"
- Reboot

### On what version of Vanilla OS this happens?

22.10

### Additional Information

Acer Predator Helios 300 with a classical BIOS, GTX 1050 ti and core I7

**Comment by mirkobrombin** [comment]
Please try the latest ISO (r6+) and let me know.
