### ISSUE TITLE
The installer keeps running forever and shows an empty log.

### ISSUE THREAD

**Issue by berserkwarwolf** [Vanilla-OS/iso-builder#76]
I flashed the image using Balena Etcher, as instructed.
The live usb works fine, but when I try to install Vanilla OS the installer keeps running forever and shows an empty log.

Any ideas?

Attached image:
![screenshot](https://i.imgur.com/54LwSdv.png)

**Comment by indicozy** [comment]
+1

**Comment by kbdharun** [comment]
> +1

This issue has been fixed in the repository a couple of days ago. It will be present in the next ISO.
