### ISSUE TITLE
Installer error when commiting new partiion.

### ISSUE THREAD

**Issue by Reya-Covey** [Vanilla-OS/iso-builder#77]
### Issue Description

The installer keeps timing out when trying to write the partition. The log output just repets like this for hours.
![Screenshot from 2023-01-08 01-14-26](https://user-images.githubusercontent.com/109026878/211178016-0017ab47-d4f1-417b-a8ed-09c6beb63f8d.png)
![Screenshot from 2023-01-08 01-10-02](https://user-images.githubusercontent.com/109026878/211178029-2d85b05d-1aec-49dd-bef2-e0a83710c069.png)

### Steps to Reproduce

Didn't change any default options in the installer. US locale and keybord settings. Entire disk chosen.

### On what version of Vanilla OS this happens?

22.10-r3

**Comment by mirkobrombin** [comment]
Unfortunately we cannot replicate this and there are not enough details to predict a fix. On the other hand, I wouldn't know what details to ask, if the installation goes through it means that there are no errors.

Feel free to try one of the latest ISOs and provide more details if they come to mind.
