### ISSUE TITLE
Problem to install new software 

### ISSUE THREAD

**Issue by cangebac** [Vanilla-OS/iso-builder#78]
### Issue Description

![Screenshot_from_2023-01-08_10-14-44](https://user-images.githubusercontent.com/73996381/211210725-6de536f9-2d14-49d5-ba27-e52c6859c1a1.png)
I just install vanilla os, so I try to install some software but it give me this problem

### Steps to Reproduce

Install vanilla os 
Open terminal
Run on terminal: apx install git

### On what version of Vanilla OS this happens?

22.10

**Comment by byteduck** [comment]
Same issue here. Tried a couple of fresh installs of vanilla, and both were completely unable to install any packages with the same error. The first time setup application also failed to install anything (but did so silently).

**Comment by cangebac** [comment]
I think it depends on the servers, for example I'm from Italy and I have this problem

**Comment by cangebac** [comment]
I think it depends on the servers, for example I'm from Italy and I have this problem

**Comment by ghost** [comment]
I'm having this issue for some packages in the software store. 

![Screenshot from 2023-01-14 21-36-13](https://user-images.githubusercontent.com/122128828/212528798-0cd21d4f-fdaa-4ce2-8f35-d7c27760d2ac.png)

**Comment by mirkobrombin** [comment]
There was an issue with the broken Ubuntu image from dockerhub at one point. Use apx init to reinitialize the container.
