### ISSUE TITLE
install-vanilla-22.10-failed

### ISSUE THREAD

**Issue by xuzhou2016** [Vanilla-OS/iso-builder#79]
### Issue Description

Hello,  I download the lastest verion 22.10 from our website,  and I want to install it  with my virtualbox  6.1.34( last version of version 6),   and my Host os is:  macOs High Sierra (version 10.13.6).   
When I start the virtualbox,  and chose the default option: Try or install  Vanilla
then errors are shown  as follows: 

### Steps to Reproduce

Just the virtual machine.

### On what version of Vanilla OS this happens?

22.10

**Comment by xuzhou2016** [comment]
This richText  editor can not upload an Image ??

**Comment by xuzhou2016** [comment]
errors are as followed:

Initramfs unpacking failed: ZSTD-compressed data is corrupt
Failed to execute /init (error -2)
.....

**Comment by mirkobrombin** [comment]
This should be fixed now.

**Comment by xuzhou2016** [comment]
Thanks really !  I will try it later.
