### ISSUE TITLE
Podman > 4

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/iso-builder#80]
### Feature Description

Podman should be at version 4 or greater.

### Rationale

None of the available Podman SDKs or clients work with the 3.x versions anymore.

### Additional Information

Upgrading Podman would allow quite a few possibilities and enable some management features.

**Comment by kbdharun** [comment]
Closing this as the Podman version is already `> 4` in <https://packages.vanillaos.org/package/podman>.
