### ISSUE TITLE
Gnome Web not uninstalling from software store

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/iso-builder#83]
### Issue Description

I've attempted to uninstall gnome web from the software store, and the software store displayed gnome web as being uninstalled. But despite the software store stating this, gnome web is still installed 
![Screenshot from 2023-01-12 17-28-54](https://user-images.githubusercontent.com/122128828/212216175-1747feb1-8d3b-4469-84ef-c20a8f7345b1.png)
![Screenshot from 2023-01-12 17-29-18](https://user-images.githubusercontent.com/122128828/212216226-fc9e5a39-d01e-4ca8-a496-0fc800e8596e.png)

### Steps to Reproduce

- Go to software
- uninstall gnome web
- then search web
- and launch gnome web lol

### On what version of Vanilla OS this happens?

22.10

### Additional Information

I am using release 3 of 22.10

**Comment by kbdharun** [comment]
Software store can't remove applications in the host. You need to remove it manually through the command line. 

Yesterday this change was applied to make these applications as optional in base. So until the next update to base I would suggest you not remove any pre-installed applications.

**Comment by ghost** [comment]
> Software store can't remove applications in the host. You need to remove it manually through the command line.
> 
> Yesterday this change was applied to make these applications as optional in base. So until the next update to base I would suggest you not remove any pre-installed applications.

Understandable, does this mean you will be able to use the "first setup" utility to overwrite the installation process? When this new build is pushed. Also, is there any roadmap documentation like the one you have for the handbook?

**Comment by kbdharun** [comment]
> Understandable, does this mean you will be able to use the "first setup" utility to overwrite the installation process?

No, I didn't get what you meant. You can remove it from the host using ABRoot in future after you receive the base update. There is a proposal in GitHub to move this entirely to first setup and remove it from base. The only disadvantage being that if flatpak is disabled then you don't get the applications.

**Comment by ghost** [comment]
> > Understandable, does this mean you will be able to use the "first setup" utility to overwrite the installation process?
> 
> No, I didn't get what you meant. You can remove it from the host using ABRoot in future after you receive the base update. There is a proposal in GitHub to move this entirely to first setup and remove it from base. The only disadvantage being that if flatpak is disabled then you don't get the applications.

I mean a feature roadmap for what's getting worked on, like the handbook roadmap here https://github.com/orgs/Vanilla-OS/projects/2/views/1 as I would like to know what planned such as encryption. I noticed when I installed vanillaOS there's no encryption option 

That makes sense, I guess one solution would to install it when Flatpak's aren't selected then give the option when Flatpak's are selected.

**Comment by kbdharun** [comment]
Wdym, feature roadmaps are available here https://github.com/orgs/Vanilla-OS/projects/1 and https://vanillaos.org/roadmap.

**Comment by ghost** [comment]
> Wdym, feature roadmaps are available here https://github.com/orgs/Vanilla-OS/projects/1 and https://vanillaos.org/roadmap.

thank, you

**Comment by mirkobrombin** [comment]
You must use ABRoot for system software.
