### ISSUE TITLE
Outdated package: yad v.0.40 (required by STL)

### ISSUE THREAD

**Issue by Zukureneno** [Vanilla-OS/iso-builder#85]
### Issue Description

yad package is outdated (Currently Debian/Ubuntu etc are using version 0.40) . [https://github.com/v1cont/yad](https://github.com/v1cont/yad) 
Official github package is 12.3.

This package is required for SteamTinkerLaunch (Protonup-QT version) to be on version 7.2 or above.
[https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad)

Process I personally followed to build it on another ubuntu based distro:

-Uninstalled yad then follow instructions at github to build it.
-[https://github.com/sonic2kk/steamtinkerlaunch/issues/123#issuecomment-721147337](https://github.com/sonic2kk/steamtinkerlaunch/issues/123#issuecomment-721147337)

### Steps to Reproduce

-Terminal: yad --version
or 
-Install protonup-QT
-Try to install STL (SteamTinkerLaunch)

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
That package is managed by Ubuntu. Please report there.
