### ISSUE TITLE
Podman can't be used directly

### ISSUE THREAD

**Issue by SamuelNorbury** [Vanilla-OS/iso-builder#88]
### Issue Description

I use the following podman container to serve my jekyll blog locally:

```
podman run \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 \
  -e JEKYLL_ROOTLESS=1 \
  -it jekyll/jekyll:4.2.0 \
   jekyll serve
```

Podman is pre-installed on vanilla, but a number of issues pop up. First, docker.io registries are not set in `/etc/containers/registries.conf`, which is easy enough to resolve but a bit painful. Second, this error shows up, and networking doesn't work at all:

```
[10:27:56] ~/projects/whatshouldyoueat (master) $ ./ci/serve.sh 
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
ERRO[0001] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
Traceback (most recent call last):
        9: from /usr/gem/bin/jekyll:23:in `<main>'
```

### Steps to Reproduce

Run this script on vanilla os 22.10:

```
podman run \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 \
  -e JEKYLL_ROOTLESS=1 \
  -it jekyll/jekyll:4.2.0 \
   jekyll serve
```

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
I have the same problem in Ubuntu, I had to sudo the command.

**Comment by SamuelNorbury** [comment]
I figured out 2 workarounds for this problem (both preventing the use of `sudo` when running podman)

1. Use `host` network, like:
```
podman run \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 \
  -e JEKYLL_ROOTLESS=1 \
  --network host \
  -it jekyll/jekyll:4.2.0 \
   jekyll serve
```

I tested this and it works perfectly fine.

2. install slirp4netns via abroot, this is the error shown above:
`sudo abroot exec apt install slirp4netns`

I actually didn't test this, but I assume it solves the problem too.

As for the registries, that's not a VanillaOS problem, but podman itself. You can run `podman run docker.io/jekyll/jekyll` or add the entry in the registries file to resolve it.
