### ISSUE TITLE
Vim appears to not be installed by default yet it already is 

### ISSUE THREAD

**Issue by buildershed** [Vanilla-OS/iso-builder#9]
Ubuntu comes with vim by default but has the binary renamed, not aliased, to vi. 
According to the package manager though, vim isn't installed and if you do sudo apt install vim , it basically installs another copy of vim as the vim binary but this time, unrenamed.

To be honest, I don't know why Ubuntu does this because vi as a command is used far, far less compared to vim as a command.

**Comment by mks-h** [comment]
The installed Vim is in minimal Vi-compatible configuration, without even user manual installed. It's the same on Fedora, and from what I can tell — this is expected for some compatibility. So, I'd say this isn't an issue at all, but if you think otherwise — that's an upstream issue of Ubuntu.
