### ISSUE TITLE
Installing not working

### ISSUE THREAD

**Issue by Zaniuk** [Vanilla-OS/iso-builder#96]
### Issue Description

Stuck on infinite loading screen. Tried both BIOS and UEFI modes, also tried flashing USB with Rufus 3.20 and Balena Etcher (lastest).

### Steps to Reproduce

- Boot USB 
- Enter in Try or Install VanillaOS
- Set English (United States) as language
- Set Latin American keyboard layout
- Set VanillaOS to use entire disk
- Set Buenos Aires, Argentina timezone
- Proceed to installation

### On what version of Vanilla OS this happens?

22.10

### Additional Information

About my system:
![Screenshot from 2023-01-19 22-01-19](https://user-images.githubusercontent.com/61323637/213596144-f606ba7f-8f4b-4664-b60d-936fb51f7e6c.png)
![Screenshot from 2023-01-19 22-00-54](https://user-images.githubusercontent.com/61323637/213596150-a835946b-ceb0-43df-a488-7f7fcebf0cea.png)

Also tried to install other ubuntu flavours and have no problem. Maybe I'm doing something wrong?

**Comment by mirkobrombin** [comment]
Potentially fixed by https://github.com/Vanilla-OS/vanilla-installer/pull/108

a new iso will be available in hours

**Comment by Zaniuk** [comment]
Working fine now. You are the best, guys!

**Comment by nopl12** [comment]
А чё делать если вообще не запускается установщик? Тупой америкос

**Comment by nijahplays** [comment]
> 

Пожалуйста, не грубите
